#!/bin/bash
PSQL_COMMAND=/usr/bin/psql
HOST=#{DB_HOST} #dev-ukre-pgs28.dc.solera-uk.com
USER=#{DB_USER.CHOX} #chox
DB=#{DB_NAME.CHOX} #dev_uk_chox

MI_DIRECTORY=/home/chox/reports/
DUMPFILE=ERAC-User_State_Report-`date +"%F"`.txt
START_DATE=`date +%Y-%m-01`
CHO_ID=1007


echo 'User state Report generating for ERAC'

$PSQL_COMMAND --pset footer -h ${HOST} -U ${USER} -d ${DB} -o ${DUMPFILE} << --EOF--
select * from choUserStateReport(${CHO_ID})
--EOF--


/bin/mv ${DUMPFILE} ${MI_DIRECTORY}

exit 0
