<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>idas</groupId>
    <artifactId>chox</artifactId>
    <packaging>pom</packaging>
    <version>2.0</version>
    <name>idas.chox</name>
    <url>https://www.idaschox.com</url>
    <modules>
        <module>idas.chox.core</module>
        <module>idas.chox.data</module>
        <module>idas.chox.service</module>
    <module>idas.chox.web</module>
  </modules>
</project>