/*
 * CHOX-724: Claim Details Report
 *  Example usage:
 *      select * from claimDetailsReport(array[6], null::integer[], null::integer[], '2017-01-01', '2017-01-01', 'INS', array['ClaimClosed','PaymentReceived','ManualInvoicePaid','ClaimRejectionAccepted','InvoiceRejectionAccepted'], array['ClaimRejected']);
 */
DROP FUNCTION claimDetailsReport(
    IN insIds INTEGER[],
    IN choIds INTEGER[],
    IN claimTypes INTEGER[],
    IN claimUploadDate VARCHAR,
    IN closedClaimDate VARCHAR,
    IN insOrCHO char(3),
    IN closedClaimStatuses VARCHAR[],
    IN openClaimStatuses VARCHAR[]);


CREATE OR REPLACE FUNCTION claimDetailsReport(
    IN insIds INTEGER[],
    IN choIds INTEGER[],
    IN claimTypes INTEGER[],
    IN claimUploadDate VARCHAR,
    IN closedClaimDate VARCHAR,
    IN insOrCHO char(3),
    IN closedClaimStatuses VARCHAR[],
    IN openClaimStatuses VARCHAR[])
RETURNS TABLE(
                "Claim Status" VARCHAR,
                "Claim Type" text,
                "SLA Days Remaining" VARCHAR(5),
                "Supplier Reference" VARCHAR,
                "CHO Name" VARCHAR,
                "Insurer Name" VARCHAR,
                "Workgroup" VARCHAR,
                "Last Review Date" text,
                "Invoice Review Required?" text,
                "Invoice Review Reason" VARCHAR,
                "Status Modified Date" text,
                "Reserve Value" numeric,
                "Liability Status" text,
                "Final Review?" text,
                "Liability % Agreed (CHO)" numeric(8,1),
                "Liability % Agreed (Insurer)" numeric(8,1),
                "Liability % Applied to Total to Pay" numeric(8,1),
                "Indemnity Stance" VARCHAR,
                "CHO Managing Repair?" text,
                "Customer Contact Date" timestamp without time zone,
                "Credit Agreement Signed by Customer Date" timestamp without time zone,
                "GTA 4.1 Notice Date" text,
                "Claim Number" VARCHAR,
                "Insurer Claim Owner" text,
                "Supplier Claim Owner" text,
                "Customer Policy Usage" VARCHAR,
                "Customer Insurer" VARCHAR,
                "Customer Policy Number" VARCHAR,
                "Customer Reference" VARCHAR,
                "Comprehensive?" text,
                "Customer Postcode" VARCHAR,
                "Customer Vehicle Manufacturer" VARCHAR,
                "Customer Vehicle Model" VARCHAR,
                "Customer Vehicle Registration" VARCHAR,
                "Customer Vehicle Year" VARCHAR,
                "Customer Vehicle Class" VARCHAR,
                "Customer Vehicle Location" VARCHAR,
                "Customer HPI Vehicle Manufacturer" VARCHAR,
                "Customer HPI Vehicle Model" VARCHAR,
                "Customer HPI Vehicle Year" VARCHAR,
                "Customer HPI Vehicle First Registration" text,
                "Customer HPI Vehicle Capacity" VARCHAR,
                "Customer HPI Vehicle Doorplan" VARCHAR,
                "Customer HPI Vehicle Transmission" VARCHAR,
                "Customer Can Access Other Vehicle?" text,
                "Customer Other Vehicle Used?" text,
                "Customer Other Vehicle" VARCHAR,
                "Customer Courtesy Car?" text,
                "Customer Specific Vehicle Required" text,
                "Customer Specific Vehicle Reason" VARCHAR,
                "Customer Vehicle Type Required" VARCHAR,
                "Customer Special Requirements" VARCHAR,
                "Customer Average Daily Milage" VARCHAR,
                "Third Party Insurer" VARCHAR,
                "Third Party Policy Number" VARCHAR,
                "Third Party Postcode" VARCHAR(16),
                "Third Party Vehicle Manufacturer" VARCHAR,
                "Third Party Vehicle Model" VARCHAR,
                "Third Party Vehicle Registration" VARCHAR,
                "Third Party Vehicle Class" VARCHAR,
                "Customer Vehicle Damage" VARCHAR,
                "Customer Vehicle Is Usable?" text,
                "Customer Is Total Loss?" text,
                "Initial ECD" timestamp without time zone,
                "Incident Date/Time" timestamp without time zone,
                "Incident Location" text,
                "Police Involved?" text,
                "Incident Description" text,
                "Engineer Report Labour Amount" numeric(8,2),
                "Engineer Report Repair Amount" numeric(8,2),
                "Engineer Report Estimated Days Under Repair" numeric,
                "Engineer Report Is Usable?" text,
                "Engineer Report Name" VARCHAR,
                "Engineer Report Company" VARCHAR,
                "Engineer Report Address1" VARCHAR,
                "Engineer Report Address2" VARCHAR,
                "Engineer Report Address3" VARCHAR,
                "Engineer Report Address4" VARCHAR,
                "Engineer Report Address5" VARCHAR,
                "Engineer Report Postcode" VARCHAR,
                "Engineer Report Telephone" VARCHAR,
                "Engineer Report Email" VARCHAR,
                "Hire Vehicle Manufacturer" VARCHAR,
                "Hire Vehicle Model" VARCHAR,
                "Hire Vehicle Registration" VARCHAR,
                "Hire Vehicle Class" VARCHAR,
                "Hire Vehicle Rental Start" timestamp without time zone,
                "Hire Vehicle Rental End" timestamp without time zone,
                "Hire Vehicle Days Hire" numeric,
                "Hire Vehicle Collection Reason" VARCHAR,
                "Hire Vehicle HPI Manufacturer" VARCHAR,
                "Hire Vehicle HPI Model" VARCHAR,
                "Hire Vehicle HPI Year" VARCHAR,
                "Hire Vehicle HPI First Registration" date,
                "Hire Vehicle HPI Capacity" VARCHAR,
                "Hire Vehicle HPI Door Plan" VARCHAR,
                "Hire Vehicle HPI Transmission" VARCHAR,
                "Name of Repairer" VARCHAR,
                "Repair Booked-in Date" timestamp without time zone,
                "Repair Authorised Date" timestamp without time zone,
                "Repair Commenced Date" timestamp without time zone,
                "Inspection Booked Date" timestamp without time zone,
                "Inspection Date" timestamp without time zone,
                "Name of IME" VARCHAR,
                "Repair Completion Date" timestamp without time zone,
                "Is Total Loss?" text,
                "Date Total Loss Offer Made" timestamp without time zone,
                "Date Total Loss Offer Accepted" timestamp without time zone,
                "Date Total Loss Cheque Issued " timestamp without time zone,
                "Date Total Loss Cheque Received " timestamp without time zone,
                "Labour Rate (per Hour)" numeric,
                "Labour Hours" numeric,
                "Total Labour Cost" numeric(10,2),
                "Labour Information Non-Provision Reason" VARCHAR,
                "Is Repair Only (No Hire)?" text,
                "Is Non-Fault Insurer Managing Repair?" text,
                "Is The Vehicle Owner VAT Registered?" text,
                "Next Review Date" timestamp without time zone,
                "Has Copley Offer been made?" text,
                "Copley Offer Made Date" timestamp without time zone
) AS $BODY$
BEGIN
RETURN QUERY

select
    c.status,
    getClaimTypeName(c.claim_type),
    c.remaining_sla_days_str,
    c.cho_reference,
    cho.name,
    ins.name,
    w.name,
    to_char(c.last_review_date, 'dd/mm/yyyy hh24:mm'),
    case when insOrCHO = 'INS' then case when c.is_invoice_review_required then 'Yes' else 'No' end else '' end,
    case when insOrCHO = 'INS' then c.invoice_review_reason else '' end,
    to_char(c.status_modified_date, 'dd/mm/yyyy hh:mm'),
    c.indeminty_amount,
    getLiabilityStatus(c.liability_status),
    case when insOrCHO = 'INS' then case when c.final_review_ins then 'Yes' else 'No' end else case when c.final_review_cho then 'Yes' else 'No' end end,
    round(c.percentage_liability_cho,1),
    round(c.percentage_liability_accepted, 1),
    round(c.applied_liability, 1),
    c.indemnity_stance,
    case when c.managing_repair then 'Yes' else 'No' end,
    c.policy_holder_contact_date,
    c.credit_agreement_date,
    to_char(c.gta_notice_date, 'dd/mm/yyyy hh24:mm'),
    c.claim_number,
    case when wu.hashed then 'GDPR: Data Removed' else wu.last_name || ', ' || wu.first_name end as claim_owner,
    case when wuc.hashed then 'GDPR: Data Removed' else wuc.last_name || ', ' || wuc.first_name end as claim_supplier_owner,
    cust.policy_usage as customer_policy_usage,
    cust.insurer_name as customer_insurer_name,
    cust.policy_number as customer_policy_number,
    cust.claim_reference as customer_claim_reference,
    case when cust.comprehensive then 'Yes' else 'No' end as customer_comprehensive,
    cust.postcode,
    replace(cust.vehicle_manufacturer, '|', '-')::varchar as customer_vehicle_manufacturer,
    replace(cust.vehicle_model, '|', '-')::varchar as customer_vehicle_model,
    cust.vehicle_registration as customer_vehicle_registration,
    cust.vehicle_year as customer_vehicle_year,
    cust_vc.name as customer_vehicle_class,
    cust.location as customer_location,
    cust.hpi_vehicle_manufacturer as customer_hpi_vehicle_manufacturer,
    cust.hpi_vehicle_model as customer_hpi_vehicle_model,
    cust.hpi_vehicle_year as customer_hpi_vehicle_year,
    to_char(cust.hpi_first_registration, 'dd/mm/yyyy') as customer_hpi_vehicle_first_registration,
    cust.hpi_vehicle_capacity as customer_hpi_vehicle_capacity,
    cust.hpi_vehicle_doorplan as customer_hpi_vehicle_doorplan,
    cust.hpi_vehicle_transmission as customer_hpi_vehicle_transmission,
    case when cust.access_other_vehicle is null then '' else case when cust.access_other_vehicle then 'Yes' else 'No' end end as customer_access_other_vehicle,
    case when cust.other_vehicle_used is null then '' else case when cust.other_vehicle_used then 'Yes' else 'No' end end as customer_other_vehicle_used,
    cust.other_vehicle as customer_other_vehicle,
    case when cust.courtesy_car is null then '' else case when cust.courtesy_car then 'Yes' else 'No' end end as customer_courtesy_car,
    case when cust.specific_vehicle is null then '' else case when cust.specific_vehicle then 'Yes' else 'No' end end as customer_specific_vehicle,
    cust.specific_vehicle_reason as customer_specific_vehicle_reason,
    cust.vehicle_type_required as customer_vehicle_type_required,
    cust.special_requirements as customer_special_requirements,
    cust.average_daily_mileage as customer_average_daily_mileage,
    tp_insurer.name as tp_insurer_name,
    tp.policy_number as tp_policy_number, tp.postcode,
    tp.vehicle_manufacturer as tp_vehicle_manufacturer,
    tp.vehicle_model as tp_vehicle_model,
    tp.vehicle_registration as tp_vehicle_registration,
    tp_vc.name as tp_vehicle_class,
    cust.damage as customer_damage,
    case when cust.is_usable is null then '' else case when cust.is_usable then 'Yes' else 'No' end end as customer_is_usable,
    case when cust.is_total_loss is null then '' else case when cust.is_total_loss then 'Yes' else 'No' end end as customer_is_total_loss,
    cust.initial_ecd as customer_initial_ecd,
    inc. date as incident_date,
    inc.location as incident_location,
    case when inc.is_police_involved is null then '' else case when inc.is_police_involved then 'Yes' else 'No' end end as incident_is_police_involved,
    regexp_replace(inc.incident_description, E'[\\n\\r]+', ' ', 'g' ) as incident_description,
    er.labour_amount as er_labour_amount,
    er.total_amount as er_repair_amount,
    er.days as er_days,
    case when er.is_usable is null then 'Unknown' else case when er.is_usable then 'Yes' else 'No' end end,
    er.name as er_name,
    er.company as er_company,
    er.address1 as er_address1,
    er.address2 as er_address2,
    er.address3 as er_address3,
    er.address4 as er_address4,
    er.address5 as er_address5,
    er.postcode as er_postcode,
    er.telephone as er_telephone,
    er.email as er_email,
    vh.vehicle_manufacturer as vh_vehicle_manufacturer, vh.vehicle_model as vh_vehicle_model, vh.vehicle_registration as vh_vehicle_registration,
    vh_vc.name as vh_vehicle_class_name, vh.rental_start as vh_rental_start, vh.rental_end as vh_rental_end, vh.days as vh_days,
    vh.collection_reason as vh_collection_reason, vh.hpi_vehicle_manufacturer as vh_hpi_vehicle_manufacturer, vh.hpi_vehicle_model as vh_hpi_vehicle_model,
    vh.hpi_vehicle_year as vh_hpi_vehicle_year, vh.hpi_first_registration as vh_hpi_vehicle_first_registration,
    vh.hpi_vehicle_capacity as vh_hpi_vehicle_capacity, vh.hpi_vehicle_doorplan as vh_hpi_vehicle_doorplan,
    vh.hpi_vehicle_transmission as vh_hpi_vehicle_transmission, hmd.name_of_repairer as hmd_name_of_repairer, hmd.repair_book_in_date as hmd_repair_book_in_date,
    hmd.repair_authorised_date as hmd_repair_authorised_date, hmd.repair_commenced_date as hmd_repair_commenced_date,
    hmd.inspection_booked_date as hmd_inspection_booked_date, hmd.inspection_date as hmd_inspection_date, hmd.name_of_ime as hmd_name_of_ime,
    hmd.repair_completion_date as hmd_repair_completion_date,
    case when hmd.is_total_lost_check is null then '' else case when hmd.is_total_lost_check then 'Yes' else 'No' end end as hmd_is_total_lost_check,
    hmd.total_loss_offer_made as hmd_total_loss_offer_made,
    hmd.total_loss_offer_accepted as hmd_total_loss_offer_accepted, hmd.total_loss_check_issued as hmd_total_loss_check_issued,
    hmd.total_loss_check_received as hmd_total_loss_check_received, hmd.labour_rate as hmd_labour_rate, hmd.labour_hour as hmd_labour_hour,
    hmd.labour_cost as hmd_labour_cost,
    hmd.non_provision_reason as hmd_non_provision_reason, 
    case when hmd.is_repair_only_check is null then '' else case when hmd.is_repair_only_check then 'Yes' else 'No' end end as claim_repair_only_check,
    case when hmd.is_non_fault_insurer_managing_repair is null then '' else case when hmd.is_non_fault_insurer_managing_repair then 'Yes' else 'No' end end as claim_non_fault_insurer_repair,
    case when hmd.client_vat_registered is null then '' else case when hmd.client_vat_registered then 'Yes' else 'No' end end as claim_client_vat_registered,
    hmd.next_review_date as hmd_next_review_date,
    case when c.copley_offer_made is null then '' else case when c.copley_offer_made then 'Yes' else 'No' end end as claim_copley_offer,
    c.copley_offer_made_date
from claim c
    join chorganisation cho on (c.chorganisation_id = cho.id)
    join insurer ins on (c.insurer_id = ins.id)
    left outer join workgroup w on (c.workgroup_id = w.id)
    left outer join web_user wu on (c.claim_owner_id = wu.id)
    left outer join web_user wuc on (c.cho_claim_owner_id = wuc.id)
    left outer join customer cust on (c.customer_id = cust.id)
    left outer join vehicle_class cust_vc on (cust.vehicle_class_id = cust_vc.id)
    left outer join third_party tp on (c.third_party_id = tp.id)
    left outer join vehicle_class tp_vc on (cust.vehicle_class_id = tp_vc.id)
    left outer join insurer tp_insurer on (tp.insurer_id = tp_insurer.id)
    left outer join incident inc on (c.incident_id = inc.id)
    left outer join witness wit on (inc.id = wit.incident_id)
    left outer join injury inj on (inc.id = inj.incident_id)
    left outer join engineer_report er on (c.engineer_report_id = er.id)
    left outer join vehicle_hire vh on (c.vehicle_hire_id = vh.id)
    left outer join vehicle_class vh_vc on (vh.vehicle_class_id = vh_vc.id)
    left outer join hire_monitoring_detail hmd on (c.hire_monitoring_detail_id = hmd.id)
where (insIds is null or c.insurer_id = ANY(insIds))
    and (choIds is null or c.chorganisation_id = ANY(choIds))
    and (claimTypes is null or c.claim_type = ANY(claimTypes))
    and c.created_date >= claimUploadDate::Date
    and ((c.status!=ALL(closedClaimStatuses) and (openClaimStatuses is null or c.status!=ALL(openClaimStatuses)))
            or ((c.status=ANY(closedClaimStatuses) or (openClaimStatuses is not null and c.status=ANY(openClaimStatuses))) and c.status_modified_date >= closedClaimDate::Date))
order by c.created_date, c.cho_reference;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;


GRANT EXECUTE ON FUNCTION claimDetailsReport(
                            IN insIds INTEGER[],
                            IN choIds INTEGER[],
                            IN claimTypes INTEGER[],
                            IN claimUploadDate VARCHAR,
                            IN closedClaimDate VARCHAR,
                            IN insOrCHO char(3),
                            IN closedClaimStatuses VARCHAR[],
                            IN openClaimStatuses VARCHAR[])
TO chox_user;
GRANT EXECUTE ON FUNCTION claimDetailsReport(
                            IN insIds INTEGER[],
                            IN choIds INTEGER[],
                            IN claimTypes INTEGER[],
                            IN claimUploadDate VARCHAR,
                            IN closedClaimDate VARCHAR,
                            IN insOrCHO char(3),
                            IN closedClaimStatuses VARCHAR[],
                            IN openClaimStatuses VARCHAR[])
TO chox_mi;
