totalHireCost = idas.chox.web.AuditReviewBigDecimalConverter
totalRepairCost = idas.chox.web.AuditReviewBigDecimalConverter
penaltyChargesPaid = idas.chox.web.AuditReviewBigDecimalConverter
hireLeakageCost = idas.chox.web.AuditReviewBigDecimalConverter
exceededRepairCost = idas.chox.web.AuditReviewBigDecimalConverter
nonABPGuidelineRepairLabourRate = idas.chox.web.AuditReviewBigDecimalConverter