#MAIL: smtp properties: used for sending emails
smtpHostName=smtp.gmail.com
smtpPort=465
smtpEmailUser=chox@idaschox.com
smtpEmailPassword=ch0x_3m4il

#Database
db.url=jdbc:postgresql://localhost:5432/chox
db.user=chox_user
db.password=ch0xpa33
