<%-- 
    Document   : insurer_board
    Created on : 02-Feb-2009, 16:19:35
    Author     : Emmanuel
--%>
<%@ page contentType="text/html; charset=UTF-8" %>
<%@ taglib uri="/struts-tags" prefix="s" %>

<table cellpadding="0" cellspacing="0" class="searchForm" style="width:99%;" border="0">
    <tr><td>                                         </td>      <td>Week To Date</td><td>Month To Date</td><td>Cumulative</td></tr>
    <tr><td nowrap>Number of Claim Notifications Submitted</td>	<td><label class="std-data-ro"><s:property value="w2DData.noOfClaimNotificationsSubmitted"/></label></td>	<td><label class="std-data-ro"><s:property value="m2DData.noOfClaimNotificationsSubmitted"/></label></td>	<td><label class="std-data-ro"><s:property value="cData.noOfClaimNotificationsSubmitted"/></label></td></tr>
    <tr><td nowrap>Number of Claim Notifications Accepted</td>	<td><label class="std-data-ro"><s:property value="w2DData.noOfClaimNotificationsAccepted"/></label></td>	<td><label class="std-data-ro"><s:property value="m2DData.noOfClaimNotificationsAccepted"/></label></td>	<td><label class="std-data-ro"><s:property value="cData.noOfClaimNotificationsAccepted"/></label></td></tr>
    <tr><td nowrap>Number of Claim Notifications Rejected</td>	<td><label class="std-data-ro"><s:property value="w2DData.noOfClaimNotificationsRejected"/></label></td>	<td><label class="std-data-ro"><s:property value="m2DData.noOfClaimNotificationsRejected"/></label></td>	<td><label class="std-data-ro"><s:property value="cData.noOfClaimNotificationsRejected"/></label></td></tr>
    <tr><td nowrap>Number of Claim Notifications Pending</td>	<td><label class="std-data-ro"><s:property value="w2DData.noOfClaimNotificationsPending"/></label></td>         <td><label class="std-data-ro"><s:property value="m2DData.noOfClaimNotificationsPending"/></label></td>         <td><label class="std-data-ro"><s:property value="cData.noOfClaimNotificationsPending"/></label></td></tr>
    <tr><td nowrap>Number of Invoices Submitted</td>                 <td><label class="std-data-ro"><s:property value="w2DData.noOfInvoicesSubmitted"/></label></td>                 <td><label class="std-data-ro"><s:property value="m2DData.noOfInvoicesSubmitted"/></label></td>                 <td><label class="std-data-ro"><s:property value="cData.noOfInvoicesSubmitted"/></label></td></tr>
    <tr><td nowrap>Value of Invoices Submitted</td>                  <td><label class="std-data-ro">£<s:property value="w2DData.valueOfInvoicesSubmitted"/></label></td>              <td><label class="std-data-ro">£<s:property value="m2DData.valueOfInvoicesSubmitted"/></label></td>              <td><label class="std-data-ro">£<s:property value="cData.valueOfInvoicesSubmitted"/></label></td></tr>
    <tr><td nowrap>Number of Invoices Accepted</td>                  <td><label class="std-data-ro"><s:property value="w2DData.noOfInvoicesAccepted"/></label></td>                  <td><label class="std-data-ro"><s:property value="m2DData.noOfInvoicesAccepted"/></label></td>                  <td><label class="std-data-ro"><s:property value="cData.noOfInvoicesAccepted"/></label></td></tr>
    <tr><td nowrap>Value of Invoices Accepted</td>                   <td><label class="std-data-ro">£<s:property value="w2DData.valueOfInvoicesAccepted"/></label></td>               <td><label class="std-data-ro">£<s:property value="m2DData.valueOfInvoicesAccepted"/></label></td>               <td><label class="std-data-ro">£<s:property value="cData.valueOfInvoicesAccepted"/></label></td></tr>
    <tr><td nowrap>Number of Invoices Rejected</td>                  <td><label class="std-data-ro"><s:property value="w2DData.noOfInvoicesRejected"/></label></td>                  <td><label class="std-data-ro"><s:property value="m2DData.noOfInvoicesRejected"/></label></td>                  <td><label class="std-data-ro"><s:property value="cData.noOfInvoicesRejected"/></label></td></tr>
    <tr><td nowrap>Value of Invoices Rejected</td>                   <td><label class="std-data-ro">£<s:property value="w2DData.valueOfInvoicesRejected"/></label></td>               <td><label class="std-data-ro">£<s:property value="m2DData.valueOfInvoicesRejected"/></label></td>               <td><label class="std-data-ro">£<s:property value="cData.valueOfInvoicesRejected"/></label></td></tr>
    <tr><td nowrap>Number of Invoices Pending</td>                   <td><label class="std-data-ro"><s:property value="w2DData.noOfInvoicesPending"/></label></td>                   <td><label class="std-data-ro"><s:property value="m2DData.noOfInvoicesPending"/></label></td>                   <td><label class="std-data-ro"><s:property value="cData.noOfInvoicesPending"/></label></td></tr>
    <tr><td nowrap>Value of Invoices Pending</td>                    <td><label class="std-data-ro">£<s:property value="w2DData.valueOfInvoicesPending"/></label></td>                <td><label class="std-data-ro">£<s:property value="m2DData.valueOfInvoicesPending"/></label></td>                <td><label class="std-data-ro">£<s:property value="cData.valueOfInvoicesPending"/></label></td></tr>
    <tr><td nowrap>Number of Invoices Close</td>                     <td><label class="std-data-ro"><s:property value="w2DData.noOfInvoicesClosed"/></label></td>                    <td><label class="std-data-ro"><s:property value="m2DData.noOfInvoicesClosed"/></label></td>                    <td><label class="std-data-ro"><s:property value="cData.noOfInvoicesClosed"/></label></td></tr>
    <tr><td nowrap>Value of Invoices Close</td>                       <td><label class="std-data-ro">£<s:property value="w2DData.valueOfInvoicesClosed"/></label></td>                 <td><label class="std-data-ro">£<s:property value="m2DData.valueOfInvoicesClosed"/></label></td>                 <td><label class="std-data-ro">£<s:property value="cData.valueOfInvoicesClosed"/></label></td></tr>
</table>


