--
-- CHOX-740: New BRE Parameter Box for new GTA Amend rules
--
ALTER TABLE bre_band
    ADD COLUMN total_loss_own_roadworthy_check boolean not null default false,
    ADD COLUMN total_loss_own_unroadworthy_check boolean not null default false,
    ADD COLUMN total_loss_cho_roadworthy_check boolean not null default false,
    ADD COLUMN total_loss_cho_unroadworthy_check boolean not null default false,
    ADD COLUMN total_loss_cho_atFault_roadworthy_check boolean not null default false,
    ADD COLUMN total_loss_cho_atFault_unroadworthy_check boolean not null default false,
    ADD COLUMN total_loss_diary_info_check boolean not null default false,
    ADD COLUMN repair_diary_info_check boolean not null default false,
    ADD COLUMN upload_414_check boolean not null default false,
    ADD COLUMN time_authorise_repair_1 integer not null default 3,
    ADD COLUMN time_off_hire_1 integer not null default 1,
    ADD COLUMN time_authorise_repair_2 integer not null default 10,
    ADD COLUMN time_off_hire_2 integer not null default 5,
    ADD COLUMN time_authorise_repair_3 integer not null default 2,
    ADD COLUMN time_submit_engineers_report_3 integer not null default 1,
    ADD COLUMN time_off_hire_3 integer not null default 1,
    ADD COLUMN allowable_days_3 integer not null default 4,
    ADD COLUMN time_instruct_engineer_4 integer not null default 1,
    ADD COLUMN time_inspect_4 integer not null default 2,
    ADD COLUMN time_authorise_repair_4 integer not null default 1,
    ADD COLUMN time_submit_engineers_report_4 integer not null default 5,
    ADD COLUMN time_off_hire_4 integer not null default 5,
    ADD COLUMN allowable_days_4 integer not null default 14,
    ADD COLUMN time_authorise_repair_5 integer not null default 2,
    ADD COLUMN time_submit_engineers_report_5 integer not null default 1,
    ADD COLUMN time_off_hire_5 integer not null default 1,
    ADD COLUMN allowable_days_5 integer not null default 4,
    ADD COLUMN time_instruct_engineer_6 integer not null default 1,
    ADD COLUMN time_inspect_6 integer not null default 2,
    ADD COLUMN time_authorise_repair_6 integer not null default 1,
    ADD COLUMN time_submit_engineers_report_6 integer not null default 1,
    ADD COLUMN time_off_hire_6 integer not null default 5,
    ADD COLUMN allowable_days_6 integer not null default 10;
