#CHO reference update job properties
emailAccount=erac.test@gmail.com
emailAccountPassword=erac.test123
privilegedUsers=patrik.bego@sherwoodcompliance.co.uk, patrik.bego@gmail.com, patrik.delo@gmail.com
updateUserName=admin@driveassist.com
updatePassword=C0mpliance
bccReceivers=patrik.bego@sherwoodcompliance.co.uk, patrik.bego@gmail.com
emailSubject=erac2
#MAIL: smtp properties
onlineSupportDefaultEmail=choxsupport@sherwoodcompliance.co.uk
smtpHostName=smtp.gmail.com
smtpPort=465
smtpEmailUser=chox@idaschox.com
smtpEmailPassword=ch0x_3m4il
#MAIL: imap properties
mailHost=imap.gmail.com
mailStoreProtocol=imaps
mailPort=993
mailFolder=INBOX