#
# Rolling file appender for chox.* packages
#
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${catalina.base}/logs/idaschox.log
log4j.appender.R.MaxFileSize=10MB
log4j.appender.R.MaxBackupIndex=10
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.appender.hpi=org.apache.log4j.RollingFileAppender
log4j.appender.hpi.File=${catalina.base}/logs/idaschox-hpi.log
log4j.appender.hpi.MaxFileSize=10MB
log4j.appender.hpi.MaxBackupIndex=10
log4j.appender.hpi.layout=org.apache.log4j.PatternLayout
log4j.appender.hpi.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.appender.H=org.apache.log4j.RollingFileAppender
log4j.appender.H.File=${catalina.base}/logs/idaschox-hibernate.log
log4j.appender.H.MaxFileSize=10MB
log4j.appender.H.MaxBackupIndex=10
log4j.appender.H.layout=org.apache.log4j.PatternLayout
log4j.appender.H.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.appender.S=org.apache.log4j.RollingFileAppender
log4j.appender.S.File=${catalina.base}/logs/idaschox-springstruts.log
log4j.appender.S.MaxFileSize=10MB
log4j.appender.S.MaxBackupIndex=10
log4j.appender.S.layout=org.apache.log4j.PatternLayout
log4j.appender.S.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.appender.C=org.apache.log4j.RollingFileAppender
log4j.appender.C.File=${catalina.base}/logs/idaschox-ehCacheManager.log
log4j.appender.C.MaxFileSize=10MB
log4j.appender.C.MaxBackupIndex=10
log4j.appender.C.layout=org.apache.log4j.PatternLayout
log4j.appender.C.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n


log4j.logger.com.opensymphony=WARN, S, mail
log4j.logger.org.apache=WARN, S, mail
log4j.logger.org.acegisecurity=WARN, S, mail
log4j.logger.org.springframework=WARN, S, mail
log4j.logger.net.sf.ehcache=WARN, C, mail
log4j.logger.org.hibernate=INFO, H, mail
log4j.additivity.org.hibernate.SQL=false

log4j.logger.idas.chox=INFO, R, mail
