#
# email appender for errors
#
log4j.appender.mail=org.apache.log4j.net.SMTPAppender
log4j.appender.mail.To=John.Dowson@SherwoodCompliance.co.uk
log4j.appender.mail.From=chox@chox-uk01.idasnetwork.com
log4j.appender.mail.SMTPHost=localhost
log4j.appender.mail.BufferSize=1
log4j.appender.mail.Subject=CHOX Application Error (Production)
log4j.appender.mail.Threshold=ERROR
log4j.appender.mail.layout=org.apache.log4j.PatternLayout
log4j.appender.mail.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

#
# Rolling file appender for chox.* packages
#
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=${catalina.base}/logs/idaschox.log
log4j.appender.R.MaxFileSize=10MB
log4j.appender.R.MaxBackupIndex=10
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n
#log4j.appender.R.Threshold=DEBUG

log4j.logger.idas.chox=INFO, R
log4j.logger.idas.chox.web.actions.ClaimActivityAction=DEBUG, R
log4j.logger.idas.chox.service.workflow.activities=DEBUG, R
log4j.logger.idas.chox.web.ActivityMonitoringAction=INFO, R

#log4j.logger.idas.chox.core.search=DEBUG, R
#log4j.logger.idas.chox.data.services.ClaimServiceImpl=DEBUG, R
log4j.logger.idas.chox.service.workflow.activities=DEBUG, R

log4j.appender.H=org.apache.log4j.RollingFileAppender
log4j.appender.H.File=${catalina.base}/logs/idaschox-hibernate.log
log4j.appender.H.MaxFileSize=10MB
log4j.appender.H.MaxBackupIndex=10
log4j.appender.H.layout=org.apache.log4j.PatternLayout
log4j.appender.H.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n
#log4j.appender.H.Threshold=INFO

log4j.logger.org.hibernate=INFO, H
log4j.additivity.org.hibernate.SQL=false
log4j.logger.org.hibernate.SQL=WARN

log4j.appender.S=org.apache.log4j.RollingFileAppender
log4j.appender.S.File=${catalina.base}/logs/idaschox-springstruts.log
log4j.appender.S.MaxFileSize=10MB
log4j.appender.S.MaxBackupIndex=10
log4j.appender.S.layout=org.apache.log4j.PatternLayout
log4j.appender.S.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n
#log4j.appender.S.Threshold=INFO


log4j.logger.com.opensymphony=WARN, S
log4j.logger.org.apache.struts2=WARN, S
log4j.logger.org.acegisecurity=WARN, S
log4j.logger.org.springframework=WARN, S
