# SAF2 global conversion goes here
# eg.
java.util.Date = idas.chox.web.DateConverter
java.math.BigDecimal = idas.chox.web.BigDecimalConverter
idas.chox.core.model.LiabilityStatus = idas.chox.web.LiabilityStatusConverter
idas.chox.core.model.Branding = idas.chox.web.BrandingConverter
idas.chox.core.model.ClaimType = idas.chox.web.ClaimTypeConverter
idas.chox.core.model.InsurerDiscountType = idas.chox.web.InsurerDiscountTypeConverter

