#!/bin/bash
echo "start to send email"
USER="chox"

#echo "" | mailx -r chox@chox.com -a /home/chox/reports/LVCHOXinvoice-`date +"%Y%m%d"`.zip -s "LV CHOX Payment Bordereau `date +"%Y%m%d"`"  michaelpaul.kemp@audatex.co.uk richard.lee2@lv.co.uk otilla.dacosta@lv.co.uk susan.tyler@lv.co.uk
#echo "" | mailx -r chox@chox.com -a /home/chox/reports/LVCHOXinvoice-`date +"%Y%m%d"`.zip -s "LV CHOX Payment Bordereau `date +"%Y%m%d"`" rafael.garcia@solera.com

echo "LV CHOX Payment Bordereau" | mail -b rafael.garcia@solera.com -r chox@chox.com -a /home/chox/reports/LVCHOXinvoice`date +"%Y%m%d"`.csv -s "LV Payment Bordereau CHOX Reports `date +"%Y%m%d"`" michaelpaul.kemp@audatex.co.uk richard.lee2@lv.co.uk otilla.dacosta@lv.co.uk susan.tyler@lv.co.uk
#echo "LV CHOX Payment Bordereau" | mail -b rafael.garcia@solera.com  -r chox@chox.com -a /home/chox/reports/LVCHOXinvoice`date +"%Y%m%d"`.csv -s "LV Payment Bordereau CHOX Report `date +"%Y%m%d"`" test@test.com
echo "email sent"
exit 0
