#!/bin/bash
PSQL_COMMAND=/usr/bin/psql
HOST=#{DB_HOST} #dev-ukre-pgs28.dc.solera-uk.com
USER=#{DB_USER.CHOX} #chox
DB=#{DB_NAME.CHOX} #dev_uk_chox
MI_DIRECTORY=/home/chox/reports/

echo "Test xml generator"

# Removes first 3 lines, last 3 lines, and strips trailing '+' and white space from intermediate lines
#    $1 - input file
#    $2 - output file
function cleanOutput {
    INFILE=$1
    OUTFILE=$2

    if [ -f ${INFILE} ]
    then
        if [ "${OS}" = "Darwin" ]
        then
            /bin/cat ${INFILE} | tail -n +3 | sed '$d' |  sed '$d'  | sed '$d' | sed s'/+$//' | sed -e's/[ \t]*$//' > ${OUTFILE}
        else
            /bin/cat ${INFILE} | tail -n +3 | head -n -2 | sed s'/+$//' | sed -e's/[ \t]*$//' > ${OUTFILE}
        fi
        /bin/rm ${INFILE}
    fi
}

# Generate an XML file from a query
#    $1 - query
#    $2 - output file
function generateXML {
    QUERY1=$1
    OUTPUT_FILE1=$2

    $PSQL_COMMAND -h ${HOST} -U ${USER} -d ${DB} -o ${OUTPUT_FILE1} << --EOF--
select query_to_xml(E'${QUERY1}', true, false, '');
--EOF--
}

# Generate XML & XSD files from a query
#    $1 - query
#    $2 - output file base: '.xml' and '.xsd' will be appended to this to
#         generate the output file names
function generateOutput {
    QUERY3=$1
    OUTPUT_FILE3=$2

    # Generate XML
    generateXML "${QUERY3}" ${OUTPUT_FILE3}.tmp
    cleanOutput ${OUTPUT_FILE3}.tmp ${OUTPUT_FILE3}.XML
}

echo 'Generating LV Weekly Claim Details Dump XML export'
DUMPFILE='LV-ClaimDetailsXMLDump-'`date +"%Y%m%d"`.xml
START_DATE=`date -d "last week" +%F`
OUTPUT_FILE=${MI_DIRECTORY}/${DUMPFILE}
#XML_QUERY='select * from claimDetailsReport(array[26], array[1007,1015,1125,1735,1008,1025,1123,1021,1016,1797], null::integer[], ''2016-01-01'', ''2021-07-01'', ''INS'', array[''ClaimClosed'',''PaymentReceived'',''ManualInvoicePaid'',''ClaimRejectionAccepted'',''InvoiceRejectionAccepted''], array[''''])'
#generateOutput "${XML_QUERY}" ${OUTPUT_FILE}

$PSQL_COMMAND -h "${HOST}" -U "${USER}" -d "${DB}" -o "${OUTPUT_FILE1}" << --EOF--
select query_to_xml(E'select * from claimDetailsReport(array[26], array[1007,1015,1125,1735,1008,1025,1123,1021,1016,1797], null::integer[], '2016-01-01', '${DATE}', 'INS', array['ClaimClosed','PaymentReceived','ManualInvoicePaid','ClaimRejectionAccepted','InvoiceRejectionAccepted'], array[''])', true, false, '');
--EOF--

exit 0
