#!/bin/bash
PSQL_COMMAND=/usr/bin/psql
HOST=#{DB_HOST} #dev-ukre-pgs28.dc.solera-uk.com
USER=#{DB_USER.CHOX} #chox
DB=#{DB_NAME.CHOX} #dev_uk_chox
MODE=#{MODE} # EXPORT - send emails and transfer files, NOEXPORT - reports generated but not delivered

DUMPFILE=Uploaded_Claims_Report-`date +"%F"`.txt
#RECIPIENTS=isabelle.lecoeuche@audatex.co.uk
RECIPIENTS=michaelpaul.kemp@valexa.com
CHO_ID=$1
CHO_NAME=$2
START_DATE=$3
END_DATE=$4

: ${CHO_ID:=1009}
: ${CHO_NAME:='ClaimFast'}
: ${START_DATE:=`date -d "yesterday" +%F`}
: ${END_DATE:=`date +%F`}

SUBJECT='Claims have been uploaded by ${CHO_NAME} - '`date +"%d/%m/%Y"`

$PSQL_COMMAND -h ${HOST} -U ${USER} -d ${DB} -o ${DUMPFILE} << --EOF--
select * from uploaded_claims_report('${START_DATE}'::varchar, '${END_DATE}'::varchar, ${CHO_ID});
--EOF--

# Get count of number of claims in the report
COUNT=`cat ${DUMPFILE} | grep row |cut -c 2-|cut -d" " -f1`

# Send email if count is > 0
if [ ${COUNT} -gt 0 ]
then
    if [ "${MODE}" -eq "EXPORT" ]; then
/usr/bin/mutt -s "${SUBJECT}" -a ${DUMPFILE} -- ${RECIPIENTS} <<  --EOF--
${COUNT} claims have been uploaded by ${CHO_NAME} from ${START_DATE} to ${END_DATE}.

Please see attached report for details:

 (${DUMPFILE})

--EOF--
    else
        echo "Uploaded Claims Report not sent: ${COUNT} claims have been uploaded by ${CHO_NAME} from ${START_DATE} to ${END_DATE}"
    fi
fi

/bin/rm ${DUMPFILE}

exit 0
