<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:tns="http://www.idaschox.com/services/CHOX/"
		xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
		xmlns:xformat="http://cxf.apache.org/bindings/xformat" 
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="CHOXService"
                xmlns:xmime="http://www.w3.org/2005/05/xmlmime"
		targetNamespace="http://www.idaschox.com/services/CHOX/"
		xmlns:chx="http://www.idaschox.com/services/CHOX/">
    <wsdl:documentation>
        Service: CHOX UploadService
        Version: 1.7.0
        Owner: Audatex
        Contact: Isabelle.Lecoeuche@audatex.co.uk
    </wsdl:documentation>

    <wsdl:types>

        <xsd:schema targetNamespace="http://www.idaschox.com/services/CHOX/"
            xmlns:chx="http://www.idaschox.com/services/CHOX/"
            elementFormDefault="qualified"
            xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
            jaxb:version="2.0"
            xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
            jaxb:extensionBindingPrefixes="xjc">
<!--            xmlns:xsd="http://www.w3.org/2001/XMLSchema" -->

    <!--  Specify simple bindings for the xjc compiler. This allows @XmlRootElement
          annotations to be generated for our elements (if/when needed) -->
            <xsd:annotation>
                <xsd:appinfo>
                    <jaxb:globalBindings typesafeEnumMaxMembers="512">
                        <xjc:simple />
                    </jaxb:globalBindings>
                </xsd:appinfo>
            </xsd:annotation>

    <!-- top-level (root) elements -->
            <xsd:element name="chox" type="chx:Chox"/>
            <xsd:element name="submissionResult" type="chx:SubmissionResult"/>
            <xsd:element name="supplierReference" type="chx:SupplierReference"/>
            <xsd:element name="supplierReference1" type="chx:SupplierReference"/>
            <xsd:element name="supplierReference2" type="chx:SupplierReference"/>
            <xsd:element name="result" type="chx:Result"/>
            <xsd:element name="ecdParam" type="chx:ECDParam"/>
            <xsd:element name="note" type="chx:Note"/>
            <xsd:element name="attachment" type="chx:Attachment"/>

    <!-- Type Definitions -->
            <!-- Non-empty string -->
            <xsd:simpleType name="NonEmptyString">
                <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                    <xsd:pattern value="[^\s].*" />
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="Empty-string">
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="" />
                </xsd:restriction>
            </xsd:simpleType>
            
             <xsd:simpleType name="NA-string">
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="N/A" />
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String8">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="8"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String16">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="16"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String32">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="32"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String50">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="50"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String64">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="64"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String128">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="128"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String160">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="160"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="String256">
                <xsd:restriction base="xsd:string">
                    <xsd:maxLength value="256"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="NonEmptyString4">
                <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                    <xsd:pattern value="[^\s].*" />
                    <xsd:maxLength value="4"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="NonEmptyString64">
                <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                    <xsd:pattern value="[^\s].*" />
                    <xsd:maxLength value="64"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="NonEmptyString128">
                <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                    <xsd:pattern value="[^\s].*" />
                    <xsd:maxLength value="128"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="SupplierReference">
                <xsd:restriction base="xsd:string">
                    <xsd:minLength value="1" />
                    <xsd:pattern value="[^\s].*" />
                    <xsd:maxLength value="128"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="Char">
                <xsd:union memberTypes="chx:YesNoType chx:Empty-string" />
            </xsd:simpleType>

            <xsd:simpleType name="Money">
                <xsd:restriction base="xsd:decimal">
                    <xsd:fractionDigits value="2"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="Money-or-empty">
                <xsd:union memberTypes="chx:Money chx:Empty-string" />
            </xsd:simpleType>

            <xsd:simpleType name="Integer-or-empty">
                <xsd:union memberTypes="xsd:integer chx:Empty-string" />
            </xsd:simpleType>

            <xsd:simpleType name="DateTime-or-empty">
                <xsd:union memberTypes="xsd:dateTime chx:Empty-string" />
            </xsd:simpleType>
            
            <xsd:simpleType name="YesNoType">
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="Y"/>
                    <xsd:enumeration value="y"/>
                    <xsd:enumeration value="N"/>
                    <xsd:enumeration value="n"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="VRN">
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="(([\d]|[a-z]|[A-Z])+ ?([\d]|[a-z]|[A-Z])*)?" />
                    <xsd:maxLength value="16"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="HireExtraType">
                <xsd:annotation>
                    <xsd:documentation>The extras type is used for the invoice hire extras.</xsd:documentation>
                </xsd:annotation>
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="Admin"/>
                    <xsd:enumeration value="Additional Driver"/>
                    <xsd:enumeration value="Automatic"/>
                    <xsd:enumeration value="Baby Seat"/>
                    <xsd:enumeration value="Miscellaneous"/>
                    <xsd:enumeration value="CDW"/>
                    <xsd:enumeration value="Delivery Collection"/>
                    <xsd:enumeration value="Dual Control"/>
                    <xsd:enumeration value="Estate"/>
                    <xsd:enumeration value="Non-standard Risk Insurance Premium"/>
                    <xsd:enumeration value="Roof Rack"/>
                    <xsd:enumeration value="Sat Nav"/>
                    <xsd:enumeration value="Tow Bars"/>
                    <xsd:enumeration value="Collaboration Protocol"/>
                    <xsd:enumeration value="VED Charge"/>
                </xsd:restriction>
            </xsd:simpleType>
            
            <xsd:simpleType name="RepairExtraType">
                <xsd:annotation>
                    <xsd:documentation>The extras type is used for the invoice repair extras.</xsd:documentation>
                </xsd:annotation>
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="Repair Admin"/>
                    <xsd:enumeration value="Repair Acquisition"/>
                    <xsd:enumeration value="Repair Parts"/>
                    <xsd:enumeration value="Repair Labour"/>
                    <xsd:enumeration value="Repair Materials"/>
                    <xsd:enumeration value="Repair Specialist"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="VisibilityString">
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="((P|p)(U|u)(B|b)(L|l)(I|i)(C|c))|((P|p)(R|r)(I|i)(V|v)(A|a)(T|t)(E|e))|(^$)"/>
                </xsd:restriction>
            </xsd:simpleType>
            
            <xsd:simpleType name="SendingPAV">
                <xsd:restriction base="xsd:token">
			<xsd:enumeration value="Customers Own Insurer"/>
			<xsd:enumeration value="CHO"/>
			<xsd:enumeration value="At Fault Insurer"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="SendingPAV-or-empty">
                <xsd:union memberTypes="chx:SendingPAV chx:Empty-string" />
            </xsd:simpleType>

            <xsd:simpleType name="VehicleClass">
                <xsd:restriction base="xsd:token">
			<xsd:enumeration value="B1"/>
			<xsd:enumeration value="B2"/>
			<xsd:enumeration value="B3"/>
			<xsd:enumeration value="B4"/>
			<xsd:enumeration value="B5"/>
			<xsd:enumeration value="B6"/>
			<xsd:enumeration value="CM1"/>
			<xsd:enumeration value="CM1A"/>
			<xsd:enumeration value="CM1EST"/>
			<xsd:enumeration value="CM1ESTA"/>
			<xsd:enumeration value="CM2"/>
			<xsd:enumeration value="CM2A"/>
			<xsd:enumeration value="CM2EST"/>
			<xsd:enumeration value="CM2ESTA"/>
			<xsd:enumeration value="CM3"/>
			<xsd:enumeration value="CM3A"/>
			<xsd:enumeration value="CM3EST"/>
			<xsd:enumeration value="CM3ESTA"/>
			<xsd:enumeration value="CP1"/>
			<xsd:enumeration value="CP1A"/>
			<xsd:enumeration value="CP1EST"/>
			<xsd:enumeration value="CP1ESTA"/>
			<xsd:enumeration value="CP2"/>
			<xsd:enumeration value="CP2A"/>
			<xsd:enumeration value="CP2EST"/>
			<xsd:enumeration value="CP2ESTA"/>
			<xsd:enumeration value="CP3"/>
			<xsd:enumeration value="CP3A"/>
			<xsd:enumeration value="CP3EST"/>
			<xsd:enumeration value="CP3ESTA"/>
			<xsd:enumeration value="CS1"/>
			<xsd:enumeration value="CS1A"/>
			<xsd:enumeration value="CS1EST"/>
			<xsd:enumeration value="CS1ESTA"/>
			<xsd:enumeration value="CS2"/>
			<xsd:enumeration value="CS2A"/>
			<xsd:enumeration value="CS2EST"/>
			<xsd:enumeration value="CS2ESTA"/>
			<xsd:enumeration value="CS3"/>
			<xsd:enumeration value="CS3A"/>
			<xsd:enumeration value="CS3EST"/>
			<xsd:enumeration value="CS3ESTA"/>
			<xsd:enumeration value="CS4"/>
			<xsd:enumeration value="CS4A"/>
			<xsd:enumeration value="CS4EST"/>
			<xsd:enumeration value="CS4ESTA"/>
			<xsd:enumeration value="CS5"/>
			<xsd:enumeration value="CS5A"/>
			<xsd:enumeration value="CS5EST"/>
			<xsd:enumeration value="CS5ESTA"/>
			<xsd:enumeration value="CV1"/>
			<xsd:enumeration value="CV1A"/>
			<xsd:enumeration value="CV1EST"/>
			<xsd:enumeration value="CV1ESTA"/>
			<xsd:enumeration value="CV2"/>
			<xsd:enumeration value="CV2A"/>
			<xsd:enumeration value="CV2EST"/>
			<xsd:enumeration value="CV2ESTA"/>
			<xsd:enumeration value="CV3"/>
			<xsd:enumeration value="CV3A"/>
			<xsd:enumeration value="CV3EST"/>
			<xsd:enumeration value="CV3ESTA"/>
			<xsd:enumeration value="CV4"/>
			<xsd:enumeration value="CV4A"/>
			<xsd:enumeration value="CV4EST"/>
			<xsd:enumeration value="CV4ESTA"/>
			<xsd:enumeration value="F1"/>
			<xsd:enumeration value="F1A"/>
			<xsd:enumeration value="F1EST"/>
			<xsd:enumeration value="F1ESTA"/>
			<xsd:enumeration value="F2"/>
			<xsd:enumeration value="F2A"/>
			<xsd:enumeration value="F2EST"/>
			<xsd:enumeration value="F2ESTA"/>
			<xsd:enumeration value="F3"/>
			<xsd:enumeration value="F3A"/>
			<xsd:enumeration value="F3EST"/>
			<xsd:enumeration value="F3ESTA"/>
			<xsd:enumeration value="F4"/>
			<xsd:enumeration value="F4A"/>
			<xsd:enumeration value="F4EST"/>
			<xsd:enumeration value="F4ESTA"/>
			<xsd:enumeration value="F5"/>
			<xsd:enumeration value="F5A"/>
			<xsd:enumeration value="F5EST"/>
			<xsd:enumeration value="F5ESTA"/>
			<xsd:enumeration value="F6"/>
			<xsd:enumeration value="F6A"/>
			<xsd:enumeration value="F6EST"/>
			<xsd:enumeration value="F6ESTA"/>
			<xsd:enumeration value="F7"/>
			<xsd:enumeration value="F7A"/>
			<xsd:enumeration value="F7EST"/>
			<xsd:enumeration value="F7ESTA"/>
			<xsd:enumeration value="F8"/>
			<xsd:enumeration value="F8A"/>
			<xsd:enumeration value="F8EST"/>
			<xsd:enumeration value="F8ESTA"/>
			<xsd:enumeration value="F9"/>
			<xsd:enumeration value="F9A"/>
			<xsd:enumeration value="F9EST"/>
			<xsd:enumeration value="F9ESTA"/>
			<xsd:enumeration value="M"/>
			<xsd:enumeration value="M1"/>
			<xsd:enumeration value="M1A"/>
			<xsd:enumeration value="M1EST"/>
			<xsd:enumeration value="M1ESTA"/>
			<xsd:enumeration value="M2"/>
			<xsd:enumeration value="M2A"/>
			<xsd:enumeration value="M2EST"/>
			<xsd:enumeration value="M2ESTA"/>
			<xsd:enumeration value="M3"/>
			<xsd:enumeration value="M3A"/>
			<xsd:enumeration value="M3EST"/>
			<xsd:enumeration value="M3ESTA"/>
			<xsd:enumeration value="M4"/>
			<xsd:enumeration value="M4A"/>
			<xsd:enumeration value="M4EST"/>
			<xsd:enumeration value="M4ESTA"/>
			<xsd:enumeration value="M5"/>
			<xsd:enumeration value="M5A"/>
			<xsd:enumeration value="M5EST"/>
			<xsd:enumeration value="M5ESTA"/>
			<xsd:enumeration value="M6"/>
			<xsd:enumeration value="M6A"/>
			<xsd:enumeration value="M6EST"/>
			<xsd:enumeration value="M6ESTA"/>
			<xsd:enumeration value="MA"/>
			<xsd:enumeration value="MEST"/>
			<xsd:enumeration value="MESTA"/>
			<xsd:enumeration value="NT3"/>
			<xsd:enumeration value="NT3A"/>
			<xsd:enumeration value="NT3EST"/>
			<xsd:enumeration value="NT3ESTA"/>
			<xsd:enumeration value="NT4"/>
			<xsd:enumeration value="NT4A"/>
			<xsd:enumeration value="NT4EST"/>
			<xsd:enumeration value="NT4ESTA"/>
			<xsd:enumeration value="P1"/>
			<xsd:enumeration value="P10"/>
			<xsd:enumeration value="P10A"/>
			<xsd:enumeration value="P10EST"/>
			<xsd:enumeration value="P10ESTA"/>
			<xsd:enumeration value="P11"/>
			<xsd:enumeration value="P11A"/>
			<xsd:enumeration value="P11EST"/>
			<xsd:enumeration value="P11ESTA"/>
			<xsd:enumeration value="P12"/>
			<xsd:enumeration value="P12A"/>
			<xsd:enumeration value="P12EST"/>
			<xsd:enumeration value="P12ESTA"/>
			<xsd:enumeration value="P13"/>
			<xsd:enumeration value="P13A"/>
			<xsd:enumeration value="P13EST"/>
			<xsd:enumeration value="P13ESTA"/>
			<xsd:enumeration value="P1A"/>
			<xsd:enumeration value="P1EST"/>
			<xsd:enumeration value="P1ESTA"/>
			<xsd:enumeration value="P2"/>
			<xsd:enumeration value="P2A"/>
			<xsd:enumeration value="P2EST"/>
			<xsd:enumeration value="P2ESTA"/>
			<xsd:enumeration value="P3"/>
			<xsd:enumeration value="P3A"/>
			<xsd:enumeration value="P3EST"/>
			<xsd:enumeration value="P3ESTA"/>
			<xsd:enumeration value="P4"/>
			<xsd:enumeration value="P4A"/>
			<xsd:enumeration value="P4EST"/>
			<xsd:enumeration value="P4ESTA"/>
			<xsd:enumeration value="P5"/>
			<xsd:enumeration value="P5A"/>
			<xsd:enumeration value="P5EST"/>
			<xsd:enumeration value="P5ESTA"/>
			<xsd:enumeration value="P6"/>
			<xsd:enumeration value="P6A"/>
			<xsd:enumeration value="P6EST"/>
			<xsd:enumeration value="P6ESTA"/>
			<xsd:enumeration value="P7"/>
			<xsd:enumeration value="P7A"/>
			<xsd:enumeration value="P7EST"/>
			<xsd:enumeration value="P7ESTA"/>
			<xsd:enumeration value="P8"/>
			<xsd:enumeration value="P8A"/>
			<xsd:enumeration value="P8EST"/>
			<xsd:enumeration value="P8ESTA"/>
			<xsd:enumeration value="P9"/>
			<xsd:enumeration value="P9A"/>
			<xsd:enumeration value="P9EST"/>
			<xsd:enumeration value="P9ESTA"/>
			<xsd:enumeration value="PT13"/>
			<xsd:enumeration value="PT13A"/>
			<xsd:enumeration value="PT13EST"/>
			<xsd:enumeration value="PT13ESTA"/>
			<xsd:enumeration value="PT9"/>
			<xsd:enumeration value="PT9A"/>
			<xsd:enumeration value="PT9EST"/>
			<xsd:enumeration value="PT9ESTA"/>
			<xsd:enumeration value="PV1"/>
			<xsd:enumeration value="PV1A"/>
			<xsd:enumeration value="PV1EST"/>
			<xsd:enumeration value="PV1ESTA"/>
			<xsd:enumeration value="PV2"/>
			<xsd:enumeration value="PV2A"/>
			<xsd:enumeration value="PV2EST"/>
			<xsd:enumeration value="PV2ESTA"/>
			<xsd:enumeration value="PV3"/>
			<xsd:enumeration value="PV3A"/>
			<xsd:enumeration value="PV3EST"/>
			<xsd:enumeration value="PV3ESTA"/>
			<xsd:enumeration value="PV4"/>
			<xsd:enumeration value="PV4A"/>
			<xsd:enumeration value="PV4EST"/>
			<xsd:enumeration value="PV4ESTA"/>
			<xsd:enumeration value="PV5"/>
			<xsd:enumeration value="PV5A"/>
			<xsd:enumeration value="PV5EST"/>
			<xsd:enumeration value="PV5ESTA"/>
			<xsd:enumeration value="PV6"/>
			<xsd:enumeration value="PV6A"/>
			<xsd:enumeration value="PV6EST"/>
			<xsd:enumeration value="PV6ESTA"/>
			<xsd:enumeration value="RV1"/>
			<xsd:enumeration value="RV1A"/>
			<xsd:enumeration value="RV1EST"/>
			<xsd:enumeration value="RV1ESTA"/>
			<xsd:enumeration value="RV2"/>
			<xsd:enumeration value="RV2A"/>
			<xsd:enumeration value="RV2EST"/>
			<xsd:enumeration value="RV2ESTA"/>
			<xsd:enumeration value="S1"/>
			<xsd:enumeration value="S1A"/>
			<xsd:enumeration value="S1EST"/>
			<xsd:enumeration value="S1ESTA"/>
			<xsd:enumeration value="S2"/>
			<xsd:enumeration value="S2A"/>
			<xsd:enumeration value="S2EST"/>
			<xsd:enumeration value="S2ESTA"/>
			<xsd:enumeration value="S3"/>
			<xsd:enumeration value="S3A"/>
			<xsd:enumeration value="S3EST"/>
			<xsd:enumeration value="S3ESTA"/>
			<xsd:enumeration value="S4"/>
			<xsd:enumeration value="S4A"/>
			<xsd:enumeration value="S4EST"/>
			<xsd:enumeration value="S4ESTA"/>
			<xsd:enumeration value="S5"/>
			<xsd:enumeration value="S5A"/>
			<xsd:enumeration value="S5EST"/>
			<xsd:enumeration value="S5ESTA"/>
			<xsd:enumeration value="S6"/>
			<xsd:enumeration value="S6A"/>
			<xsd:enumeration value="S6EST"/>
			<xsd:enumeration value="S6ESTA"/>
			<xsd:enumeration value="S7"/>
			<xsd:enumeration value="S7A"/>
			<xsd:enumeration value="S7EST"/>
			<xsd:enumeration value="S7ESTA"/>
			<xsd:enumeration value="SP1"/>
			<xsd:enumeration value="SP10"/>
			<xsd:enumeration value="SP10A"/>
			<xsd:enumeration value="SP10EST"/>
			<xsd:enumeration value="SP10ESTA"/>
			<xsd:enumeration value="SP11"/>
			<xsd:enumeration value="SP11A"/>
			<xsd:enumeration value="SP11EST"/>
			<xsd:enumeration value="SP11ESTA"/>
			<xsd:enumeration value="SP12"/>
			<xsd:enumeration value="SP12A"/>
			<xsd:enumeration value="SP12EST"/>
			<xsd:enumeration value="SP12ESTA"/>
			<xsd:enumeration value="SP13"/>
			<xsd:enumeration value="SP13A"/>
			<xsd:enumeration value="SP13EST"/>
			<xsd:enumeration value="SP13ESTA"/>
			<xsd:enumeration value="SP1A"/>
			<xsd:enumeration value="SP1EST"/>
			<xsd:enumeration value="SP1ESTA"/>
			<xsd:enumeration value="SP2"/>
			<xsd:enumeration value="SP2A"/>
			<xsd:enumeration value="SP2EST"/>
			<xsd:enumeration value="SP2ESTA"/>
			<xsd:enumeration value="SP3"/>
			<xsd:enumeration value="SP3A"/>
			<xsd:enumeration value="SP3EST"/>
			<xsd:enumeration value="SP3ESTA"/>
			<xsd:enumeration value="SP4"/>
			<xsd:enumeration value="SP4A"/>
			<xsd:enumeration value="SP4EST"/>
			<xsd:enumeration value="SP4ESTA"/>
			<xsd:enumeration value="SP5"/>
			<xsd:enumeration value="SP5A"/>
			<xsd:enumeration value="SP5EST"/>
			<xsd:enumeration value="SP5ESTA"/>
			<xsd:enumeration value="SP6"/>
			<xsd:enumeration value="SP6A"/>
			<xsd:enumeration value="SP6EST"/>
			<xsd:enumeration value="SP6ESTA"/>
			<xsd:enumeration value="SP7"/>
			<xsd:enumeration value="SP7A"/>
			<xsd:enumeration value="SP7EST"/>
			<xsd:enumeration value="SP7ESTA"/>
			<xsd:enumeration value="SP8"/>
			<xsd:enumeration value="SP8A"/>
			<xsd:enumeration value="SP8EST"/>
			<xsd:enumeration value="SP8ESTA"/>
			<xsd:enumeration value="SP9"/>
			<xsd:enumeration value="SP9A"/>
			<xsd:enumeration value="SP9EST"/>
			<xsd:enumeration value="SP9ESTA"/>
			<xsd:enumeration value="T1"/>
			<xsd:enumeration value="T10"/>
			<xsd:enumeration value="T10A"/>
			<xsd:enumeration value="T10EST"/>
			<xsd:enumeration value="T10ESTA"/>
			<xsd:enumeration value="T12"/>
			<xsd:enumeration value="T12A"/>
			<xsd:enumeration value="T12EST"/>
			<xsd:enumeration value="T12ESTA"/>
			<xsd:enumeration value="T13"/>
			<xsd:enumeration value="T13A"/>
			<xsd:enumeration value="T13EST"/>
			<xsd:enumeration value="T13ESTA"/>
			<xsd:enumeration value="T14"/>
			<xsd:enumeration value="T14A"/>
			<xsd:enumeration value="T14EST"/>
			<xsd:enumeration value="T14ESTA"/>
			<xsd:enumeration value="T1A"/>
			<xsd:enumeration value="T1EST"/>
			<xsd:enumeration value="T1ESTA"/>
			<xsd:enumeration value="T2"/>
			<xsd:enumeration value="T2A"/>
			<xsd:enumeration value="T2EST"/>
			<xsd:enumeration value="T2ESTA"/>
			<xsd:enumeration value="T3"/>
			<xsd:enumeration value="T3A"/>
			<xsd:enumeration value="T3EST"/>
			<xsd:enumeration value="T3ESTA"/>
			<xsd:enumeration value="T4"/>
			<xsd:enumeration value="T4A"/>
			<xsd:enumeration value="T4EST"/>
			<xsd:enumeration value="T4ESTA"/>
			<xsd:enumeration value="T5"/>
			<xsd:enumeration value="T5A"/>
			<xsd:enumeration value="T5EST"/>
			<xsd:enumeration value="T5ESTA"/>
			<xsd:enumeration value="T6"/>
			<xsd:enumeration value="T6A"/>
			<xsd:enumeration value="T6EST"/>
			<xsd:enumeration value="T6ESTA"/>
			<xsd:enumeration value="T7"/>
			<xsd:enumeration value="T7A"/>
			<xsd:enumeration value="T7EST"/>
			<xsd:enumeration value="T7ESTA"/>
			<xsd:enumeration value="T8"/>
			<xsd:enumeration value="T8A"/>
			<xsd:enumeration value="T8EST"/>
			<xsd:enumeration value="T8ESTA"/>
			<xsd:enumeration value="T9"/>
			<xsd:enumeration value="T9A"/>
			<xsd:enumeration value="T9EST"/>
			<xsd:enumeration value="T9ESTA"/>
			<xsd:enumeration value="UNATTACHED"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="VehicleClass-or-Empty">
                <xsd:union memberTypes="chx:VehicleClass chx:Empty-string" />
            </xsd:simpleType>
            
            <xsd:simpleType name="VehicleClass-or-Empty-or-NA">
                <xsd:union memberTypes="chx:VehicleClass chx:Empty-string chx:NA-string" />
            </xsd:simpleType>

            <xsd:complexType name="RentalVehicle">
                <xsd:sequence>
                    <xsd:element name="vehicle-registration" type="chx:String8"/>
                    <xsd:element name="vehicle-manufacturer" type="chx:String64"/>
                    <xsd:element name="vehicle-model" type="chx:String64"/>
                    <xsd:element name="vehicle-class" type="chx:VehicleClass-or-Empty"/>
                    <xsd:element name="rental-start" type="chx:DateTime-or-empty"/>
                    <xsd:element name="rental-end" type="chx:DateTime-or-empty"/>
                    <xsd:element name="collection-reason" type="chx:String128"/>
                    <xsd:element name="rental-days" type="chx:Integer-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Driver">
                <xsd:sequence>
                    <xsd:element name="title" type="chx:String64"/>
                    <xsd:element name="firstnames" type="chx:String128"/>
                    <xsd:element name="lastname" type="chx:String64"/>
                    <xsd:element name="address1" type="chx:String128"/>
                    <xsd:element name="address2" type="chx:String128"/>
                    <xsd:element name="address3" type="chx:String128"/>
                    <xsd:element name="address4" type="chx:String128"/>
                    <xsd:element name="address5" type="chx:String128"/>
                    <xsd:element name="postcode" type="chx:String16"/>
                    <xsd:element name="telephone-day" type="chx:String50"/>
                    <xsd:element name="telephone-evening" type="chx:String50"/>
                    <xsd:element name="email" type="chx:String64"/>
                    <xsd:element name="age" type="chx:Integer-or-empty"/>
                    <xsd:element name="occupation" type="chx:String64"/>
                    <xsd:element name="policy-usage" type="chx:String256"/>
                </xsd:sequence>
            </xsd:complexType>



            <xsd:complexType name="EngineerReport">
                <xsd:sequence>
                    <xsd:element name="labour-amount" type="chx:Money-or-empty"/>
                    <xsd:element name="total-amount" type="chx:Money-or-empty"/>
                    <xsd:element name="days" type="chx:Integer-or-empty"/>
                    <xsd:element name="usable" type="chx:Char"/>
                    <xsd:element name="name" type="chx:String128"/>
                    <xsd:element name="company" type="chx:String128"/>
                    <xsd:element name="address1" type="chx:String128"/>
                    <xsd:element name="address2" type="chx:String128"/>
                    <xsd:element name="address3" type="chx:String128"/>
                    <xsd:element name="address4" type="chx:String128"/>
                    <xsd:element name="address5" type="chx:String128"/>
                    <xsd:element name="postcode" type="chx:String16"/>
                    <xsd:element name="telephone" type="chx:String50"/>
                    <xsd:element name="email" type="chx:String64"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="RepairDetails">
                <xsd:sequence>
                    <xsd:element name="repairer" type="chx:String128"/>
                    <xsd:element name="inspection-booked-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="inspection-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="repair-book-in-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="repair-authorised-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="repair-started-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="repair-complete-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="name-ime" type="xsd:string"/>
                    <xsd:element name="labour-rate" type="chx:Money-or-empty"/>
                    <xsd:element name="labour-hours" type="chx:Money-or-empty"/>
                    <xsd:element name="labour-cost" type="chx:Money-or-empty"/>
                    <xsd:element name="tl-offer-made-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="tl-offer-accepted-date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="tl-cheque-issued" type="chx:DateTime-or-empty"/>
                    <xsd:element name="tl-cheque-received" type="chx:DateTime-or-empty"/>
                    <xsd:element name="tl-who-is-sending-PAV" type="chx:SendingPAV-or-empty"/>
                    <xsd:element name="engineers-report-date" type="chx:DateTime-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Repair">
                <xsd:sequence>
                    <xsd:element name="engineer-report" type="chx:EngineerReport"/>
                    <xsd:element name="repair-details" type="chx:RepairDetails"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="CustomerInsurer">
                <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"/>
                    <xsd:element name="policy-number" type="chx:String32"/>
                    <xsd:element name="claim-number" type="chx:String64"/>
                    <xsd:element name="comprehensive" type="chx:Char"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="CustomerVehicle">
                <xsd:sequence>
                    <xsd:element name="vehicle-registration" type="chx:VRN"/>
                    <xsd:element name="vehicle-manufacturer" type="chx:String64"/>
                    <xsd:element name="vehicle-model" type="chx:String64"/>
                    <xsd:element name="year-of-manufacture" type="chx:String8"/>
                    <xsd:element name="vehicle-class" type="chx:VehicleClass-or-Empty"/>
                    <xsd:element name="location" type="chx:String160"/>
                    <xsd:element name="damage" type="xsd:string"/>
                    <xsd:element name="usable" type="chx:Char"/>
                    <xsd:element name="total-loss" type="chx:Char"/>
                    <xsd:element name="initial-ecd" type="chx:DateTime-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Mitigation">
                <xsd:sequence>
                    <xsd:element name="access-another-vehicle" type="chx:Char"/>
                    <xsd:element name="other-vehicle" type="chx:String64"/>
                    <xsd:element name="other-vehicle-regular-user" type="chx:Char"/>
                    <xsd:element name="entitled-courtesy-car" type="chx:Char"/>
                    <xsd:element name="specific-required" type="chx:Char"/>
                    <xsd:element name="why-specific" type="xsd:string"/>
                    <xsd:element name="type-required" type="xsd:string"/>
                    <xsd:element name="special-requirements" type="xsd:string"/>
                    <xsd:element name="ave-daily-mileage" type="chx:String16"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Customer">
                <xsd:sequence>
                    <xsd:element name="insurer" type="chx:CustomerInsurer"/>
                    <xsd:element name="vehicle" type="chx:CustomerVehicle"/>
                    <xsd:element name="mitigation" type="chx:Mitigation"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="ThirdPartyInsurer">
                <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"/>
                    <xsd:element name="policy-number" type="chx:String32"/>
                    <xsd:element name="claim-number" type="chx:String64"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="ThirdPartyVehicle">
                <xsd:sequence>
                    <xsd:element name="vehicle-registration" type="chx:VRN"/>
                    <xsd:element name="vehicle-manufacturer" type="chx:String64"/>
                    <xsd:element name="vehicle-model" type="chx:String64"/>
                    <xsd:element name="vehicle-class" type="chx:VehicleClass-or-Empty-or-NA"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="ThirdPartyDriver">
                <xsd:sequence>
                    <xsd:element name="title" type="chx:String128"/>
                    <xsd:element name="firstnames" type="chx:String128"/>
                    <xsd:element name="lastname" type="chx:String64"/>
                    <xsd:element name="address1" type="chx:String128"/>
                    <xsd:element name="address2" type="chx:String128"/>
                    <xsd:element name="address3" type="chx:String128"/>
                    <xsd:element name="address4" type="chx:String128"/>
                    <xsd:element name="address5" type="chx:String128"/>
                    <xsd:element name="postcode" type="chx:String16"/>
                    <xsd:element name="telephone-day" type="chx:String50"/>
                    <xsd:element name="telephone-evening" type="chx:String50"/>
                    <xsd:element name="email" type="chx:String64"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="ThirdParty">
                <xsd:sequence>
                    <xsd:element name="insurer" type="chx:ThirdPartyInsurer"/>
                    <xsd:element name="vehicle" type="chx:ThirdPartyVehicle"/>
                    <xsd:element name="driver" type="chx:ThirdPartyDriver"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Witness">
                <xsd:sequence>
                    <xsd:element name="name" type="chx:String128"/>
                    <xsd:element name="address1" type="chx:String128"/>
                    <xsd:element name="address2" type="chx:String128"/>
                    <xsd:element name="address3" type="chx:String128"/>
                    <xsd:element name="address4" type="chx:String128"/>
                    <xsd:element name="address5" type="chx:String128"/>
                    <xsd:element name="postcode" type="chx:String16"/>
                    <xsd:element name="telephone-day" type="chx:String50"/>
                    <xsd:element name="telephone-evening" type="chx:String50"/>
                    <xsd:element name="email" type="chx:String64"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Solicitor">
                <xsd:sequence>
                    <xsd:element name="name" type="chx:String64"/>
                    <xsd:element name="address1" type="chx:String128"/>
                    <xsd:element name="address2" type="chx:String128"/>
                    <xsd:element name="address3" type="chx:String128"/>
                    <xsd:element name="address4" type="chx:String128"/>
                    <xsd:element name="address5" type="chx:String128"/>
                    <xsd:element name="postcode" type="chx:String16"/>
                    <xsd:element name="telephone" type="chx:String50"/>
                    <xsd:element name="email" type="chx:String64"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Injury">
                <xsd:sequence>
                    <xsd:element name="name" type="chx:String128"/>
                    <xsd:element name="address1" type="chx:String128"/>
                    <xsd:element name="address2" type="chx:String128"/>
                    <xsd:element name="address3" type="chx:String128"/>
                    <xsd:element name="address4" type="chx:String128"/>
                    <xsd:element name="address5" type="chx:String128"/>
                    <xsd:element name="postcode" type="chx:String16"/>
                    <xsd:element name="telephone-day" type="chx:String50"/>
                    <xsd:element name="telephone-evening" type="chx:String50"/>
                    <xsd:element name="email" type="chx:String64"/>
                    <xsd:element name="solicitor" type="chx:Solicitor"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Incident">
                <xsd:sequence>
                    <xsd:element name="date" type="chx:DateTime-or-empty"/>
                    <xsd:element name="location" type="xsd:string"/>
                    <xsd:element name="police-involved" type="chx:Char"/>
                    <xsd:element name="description" type="xsd:string"/>
                    <xsd:element name="witness" type="chx:Witness"/>
                    <xsd:element name="injury" type="chx:Injury"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Claim">
                <xsd:sequence>
                    <xsd:element name="customer"  type="chx:Customer"/>
                    <xsd:element name="third-party"  type="chx:ThirdParty"/>
                    <xsd:element name="incident"  type="chx:Incident"/>
                </xsd:sequence>
            </xsd:complexType>



            <xsd:complexType name="Costs">
                <xsd:sequence>
                    <xsd:element name="net" type="chx:Money-or-empty"/>
                    <xsd:element name="vat" type="chx:Money-or-empty"/>
                    <xsd:element name="gross" type="chx:Money-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>


            <xsd:complexType name="Supplier">
                <xsd:sequence>
                    <xsd:element name="excess-collected" type="chx:Money-or-empty"/>
                    <xsd:element name="vat-collected" type="chx:Money-or-empty"/>
                    <xsd:element name="handling-invoice-no" type="chx:String128"/>
                    <xsd:element name="handling-invoice-amount" type="chx:Money-or-empty"/>
                    <xsd:element name="claim-invoice-no" type="chx:String128"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="HireExtra">
                <xsd:sequence>
                    <xsd:element name="name" type="chx:HireExtraType"/>
                    <xsd:element name="quantity" type="chx:Integer-or-empty"/>
                    <xsd:element name="item-cost" type="chx:Money-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="RepairExtra">
                <xsd:sequence>
                    <xsd:element name="name"  type="chx:RepairExtraType"/>
                    <xsd:element name="item-cost" type="chx:Money-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>
            
            <xsd:complexType name="Extras">
                <xsd:sequence>
                    <xsd:element name="cover-note-required" type="chx:Char"/>
                    <xsd:element name="extra" minOccurs="0" maxOccurs="unbounded" type="chx:HireExtra"/>
                </xsd:sequence>
            </xsd:complexType>
            
            <xsd:complexType name="RepairExtras">
                <xsd:sequence>
                    <xsd:element name="extra" minOccurs="1" maxOccurs="6" type="chx:RepairExtra"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Vehicles">
                <xsd:sequence>
                    <xsd:element name="day-rate" type="chx:Money-or-empty"/>
                    <xsd:element name="net" type="chx:Money-or-empty"/>
                    <xsd:element name="vat" type="chx:Money-or-empty"/>
                    <xsd:element name="gross" type="chx:Money-or-empty"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Invoice">
                <xsd:sequence>
                    <xsd:element name="less-handling-fee" type="chx:Money-or-empty"/>
                    <xsd:element name="net" type="chx:Money-or-empty"/>
                    <xsd:element name="vat" type="chx:Money-or-empty"/>
                    <xsd:element name="gross" type="chx:Money-or-empty"/>
                    <xsd:element name="less-discount" type="chx:Money-or-empty"/>
                    <xsd:element name="total-to-pay" type="chx:Money-or-empty"/>
                    <xsd:element name="date-invoiced" type="chx:DateTime-or-empty"/>
                    <xsd:element name="vehicles" type="chx:Vehicles"/>
                    <xsd:element name="extras" minOccurs="0" type="chx:Extras"/>
                    <xsd:element name="repairExtras" minOccurs="0" type="chx:RepairExtras"/>
                    <xsd:element name="supplier" type="chx:Supplier"/>
                    <xsd:element name="repair" type="chx:Costs"/>
                    <xsd:element name="storage-recovery" type="chx:Costs"/>
                    <xsd:element name="engineer-fee" type="chx:Costs"/>
                    <xsd:element name="total-loss" type="chx:Costs"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Chox">
                <xsd:sequence>
                    <xsd:element name="macroversion" minOccurs="0" type="xsd:decimal"/>
                    <xsd:element name="xmlversion" minOccurs="0" type="xsd:decimal"/>
                    <xsd:element name="rental" minOccurs="1" maxOccurs="1" > <!-- N.B. maxOccurs="unbounded" for bordereau upload -->
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="first-contact" type="xsd:dateTime"/>
                                <xsd:element name="note" type="xsd:string"/>
                                <xsd:element name="supplier-name" minOccurs="0" type="chx:NonEmptyString128"/>
                                <xsd:element name="supplier-reference" type="chx:NonEmptyString128"/>
                                <xsd:element name="managing-repair" type="chx:YesNoType"/>
                                <xsd:element name="agreement-signed" type="chx:DateTime-or-empty"/>
                                <xsd:element name="gta-notice" type="chx:DateTime-or-empty"/>
                                <xsd:element name="invoice" type="chx:Invoice"/>
                                <xsd:element name="hire-state" type="chx:NonEmptyString"/>
                                <xsd:element name="rental-vehicle" type="chx:RentalVehicle"/>
                                <xsd:element name="driver" type="chx:Driver"/>
                                <xsd:element name="claim" type="chx:Claim"/>
                                <xsd:element name="repair" type="chx:Repair"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:simpleType name="ClaimStatus">
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="N/A"/>
                    <xsd:enumeration value="AwaitingCarHireInfo"/>
                    <xsd:enumeration value="AwaitingInvoiceData"/>
                    <xsd:enumeration value="AwaitingInvoicePayment"/>
                    <xsd:enumeration value="AwaitingLiabilityResolution"/>
                    <xsd:enumeration value="ClaimClosed"/>
                    <xsd:enumeration value="ClaimPending"/>
                    <xsd:enumeration value="ClaimReferredToEngineer"/>
                    <xsd:enumeration value="ClaimReferredToFNOL"/>
                    <xsd:enumeration value="ClaimRejected"/>
                    <xsd:enumeration value="ClaimRejectionAccepted"/>
                    <xsd:enumeration value="ClaimRejectionContested"/>
                    <xsd:enumeration value="ClaimUnacknowledgedRouted"/>
                    <xsd:enumeration value="ClaimUnacknowledgedUnassigned"/>
                    <xsd:enumeration value="ClaimUnacknowledgedUnrouted"/>
                    <xsd:enumeration value="ClaimUpdatedByEngineer"/>
                    <xsd:enumeration value="ContestedInvoiceReferredToCHO"/>
                    <xsd:enumeration value="ContestedInvoiceReferredToInsurer"/>
                    <xsd:enumeration value="InvoiceApprovedByBRE"/>
                    <xsd:enumeration value="InvoiceDataCalculationIncorrect"/>
                    <xsd:enumeration value="InvoiceEscalated"/>
                    <xsd:enumeration value="InvoiceEscalatedToHandler"/>
                    <xsd:enumeration value="InvoicePaymentLogged"/>
                    <xsd:enumeration value="InvoiceReferredToClaimsHandler"/>
                    <xsd:enumeration value="InvoiceReferredToEngineer"/>
                    <xsd:enumeration value="InvoiceRejectionAccepted"/>
                    <xsd:enumeration value="InvoiceUnassigned"/>
                    <xsd:enumeration value="ManualInvoiceBREApproved"/>
                    <xsd:enumeration value="ManualInvoiceBRERejected"/>
                    <xsd:enumeration value="ManualInvoiceContested"/>
                    <xsd:enumeration value="ManualInvoiceUnassigned"/>
                    <xsd:enumeration value="AwaitingLitigationOutcome"/>
                    <xsd:enumeration value="ManualInvoicePaid"/>
                    <xsd:enumeration value="PaymentReceived"/>
                    <xsd:enumeration value="SubscriberClaimRejected"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="ClaimUploadStatus">
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="New Invoice"/>
                    <xsd:enumeration value="Hire Monitoring and New Invoice"/>
                    <xsd:enumeration value="Hire Monitoring"/>
                    <xsd:enumeration value="New Claim"/>
                    <xsd:enumeration value="New Subscriber Claim"/>
                    <xsd:enumeration value="New Fixed Fee Claim"/>
                    <xsd:enumeration value="Claim Closed or Pending"/>
                    <xsd:enumeration value="Claim Already Exists"/>
                    <xsd:enumeration value="Claim Already Exists (Subscriber)"/>
                    <xsd:enumeration value="Claim Already Exists (Fixed Fee)"/>
                    <xsd:enumeration value="Invoice Already Exists"/>
                    <xsd:enumeration value="Incorrect Hire State"/>
                    <xsd:enumeration value="Incorrect XML Structure"/>
                    <xsd:enumeration value="Incorrect Value Provided for Hire State"/>
                    <xsd:enumeration value="Insurer is not accepting TPI invoices"/>
                    <xsd:enumeration value="Insurer is not accepting Subscriber Claims"/>
                    <xsd:enumeration value="Insurer is not accepting Fixed Fee Claims"/>
                    <xsd:enumeration value="New TPI Claim"/>
                    <xsd:enumeration value="New Invoice (Insurer vs Insurer)"/>
                    <xsd:enumeration value="Supplementary Invoice Already Exists"/>
                    <xsd:enumeration value="New Supplementary Invoice"/>
                    <xsd:enumeration value="Invalid Claim Status"/>
                    <xsd:enumeration value="New Insurer Invoice"/>
                    <xsd:enumeration value="Error"/>
                    <xsd:enumeration value="New Insurer Claim"/>
                    <xsd:enumeration value="Insurer Claim Already Exists"/>
                    <xsd:enumeration value="Insurer Hire Monitoring and New Invoice"/>
                    <xsd:enumeration value="Insurer Hire Monitoring"/>
                    <xsd:enumeration value="Insurer Invoice Already Exists"/>
                    <xsd:enumeration value="New Insurer Supplementary Invoice"/>
                    <xsd:enumeration value="Claim Already Exists But As A Different Claim Type"/>
                    <xsd:enumeration value="New Collaboration Protocol Claim"/>
                    <xsd:enumeration value="Claim Already Exists (Collaboration Protocol)"/>
                    <xsd:enumeration value="Insurer is not accepting Collaboration Protocol Claims"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:simpleType name="ClaimProcessStatus">
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="Failed"/>
                    <xsd:enumeration value="Uploaded"/>
                    <xsd:enumeration value="Updated"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:complexType name="SubmissionResult">
                <xsd:sequence>
                    <xsd:element name="status" type="xsd:boolean"/>
                    <xsd:element name="uploadStatus" type="chx:ClaimUploadStatus"/>
                    <xsd:element name="processStatus" type="chx:ClaimProcessStatus"/>
                    <xsd:element name="claimStatus" type="chx:ClaimStatus"/>
                    <xsd:element name="Messages" minOccurs="0" maxOccurs="1">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="message" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="BREMessages" minOccurs="0" maxOccurs="1">
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element name="message" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:complexType name="Result">
                <xsd:sequence>
                    <xsd:element name="status" type="xsd:boolean"/>
                    <xsd:element name="errorMessage" minOccurs="0" type="xsd:string"/>
                </xsd:sequence>
            </xsd:complexType>
            
            <xsd:complexType name="ECDParam">
                <xsd:sequence>
                    <xsd:element name="supplierReference" type="chx:NonEmptyString128"/>
                    <xsd:element name="ecdDate" type="xsd:dateTime"/>
                    <xsd:element name="delayReason" type="chx:NonEmptyString"/>
                    <xsd:element name="supportingNote" type="chx:NonEmptyString"/>
                </xsd:sequence>
            </xsd:complexType>
            
            <xsd:complexType name="Note">
                <xsd:sequence>
                    <xsd:element name="supplierReference" type="chx:NonEmptyString128"/>
                    <xsd:element name="comment" type="chx:NonEmptyString"/>
                    <xsd:element name="visibility" type="chx:VisibilityString"/>
                </xsd:sequence>
            </xsd:complexType>

            <xsd:simpleType name="AttachmentCategory">
                <xsd:restriction base="xsd:token">
                    <xsd:enumeration value="Payment Pack"/>
                    <xsd:enumeration value="Total Loss Inspection Check"/>
                    <xsd:enumeration value="CHO's Client Allegations"/>
                    <xsd:enumeration value="Insurer's Client Allegations"/>
                    <xsd:enumeration value="Engineer's Reports"/>
                    <xsd:enumeration value="Investigator Reports"/>
                    <xsd:enumeration value="Repair Documents"/>
                    <xsd:enumeration value="Repairer Statement"/>
                    <xsd:enumeration value="Total Loss Pack"/>
                    <xsd:enumeration value="Total Loss Notification"/>
                    <xsd:enumeration value="Witness Statement"/>
                    <xsd:enumeration value="Mitigation Statement"/>
                    <xsd:enumeration value="Intervention Letter"/>
                    <xsd:enumeration value="Video Footage"/>
                    <xsd:enumeration value="Other"/>
                </xsd:restriction>
            </xsd:simpleType>

            <xsd:complexType name="Attachment">
                <xsd:sequence>
                    <xsd:element name="supplierReference" type="chx:NonEmptyString128"/>
                    <xsd:element name="attachment" type="xsd:base64Binary" xmime:expectedContentTypes="application/octet-stream"/>
                    <xsd:element name="filename" type="chx:NonEmptyString"/>
                    <xsd:element name="fileType" type="chx:NonEmptyString4"/>
                    <xsd:element name="category" type="chx:AttachmentCategory"/>
                    <xsd:element name="remark" type="chx:NonEmptyString"/>
                    <xsd:element name="notify" type="xsd:boolean"/>
                </xsd:sequence>
            </xsd:complexType>

        </xsd:schema>

    </wsdl:types>


    <wsdl:message name="chox">
        <wsdl:part element="chx:chox" name="chox" />
    </wsdl:message>

    <wsdl:message name="submissionResult">
        <wsdl:part element="chx:submissionResult" name="submissionResult" />
    </wsdl:message>

    <wsdl:message name="supplierReference">
        <wsdl:part element="chx:supplierReference" name="supplierReference" />
    </wsdl:message>

    <wsdl:message name="supplierReference1">
        <wsdl:part element="chx:supplierReference1" name="supplierReference1" />
    </wsdl:message>

    <wsdl:message name="supplierReference2">
        <wsdl:part element="chx:supplierReference2" name="supplierReference2" />
    </wsdl:message>

    <wsdl:message name="result">
        <wsdl:part element="chx:result" name="result" />
    </wsdl:message>
    
    <wsdl:message name="ecdParam">
        <wsdl:part element="chx:ecdParam" name="ecdParam" />
    </wsdl:message>
    
    <wsdl:message name="note">
        <wsdl:part element="chx:note" name="note" />
    </wsdl:message>

    <wsdl:message name="attachment">
        <wsdl:part element="chx:attachment" name="attachment" />
    </wsdl:message>

    <wsdl:portType name="UploadService">
        <wsdl:documentation>Description of the business interface. These are the services provided.</wsdl:documentation>
        <jaxws:bindings xmlns:jaxws="http://java.sun.com/xml/ns/jaxws">
            <jaxws:enableWrapperStyle>false</jaxws:enableWrapperStyle>
        </jaxws:bindings>

        <wsdl:operation name="uploadBordereau">
            <wsdl:input message="tns:chox" name="chox"/>
            <wsdl:output message="tns:submissionResult" name="submissionResult"/>
        </wsdl:operation>

        <wsdl:operation name="paymentReceived">
            <wsdl:input message="tns:supplierReference" name="supplierReference"/>
            <wsdl:output message="tns:result" name="result"/>
        </wsdl:operation>

        <wsdl:operation name="closeClaim">
            <wsdl:input message="tns:supplierReference1" name="supplierReference1"/>
            <wsdl:output message="tns:result" name="result1"/>
        </wsdl:operation>

        <wsdl:operation name="reopenClaim">
            <wsdl:input message="tns:supplierReference2" name="supplierReference2"/>
            <wsdl:output message="tns:result" name="result2"/>
        </wsdl:operation>
        
        <wsdl:operation name="updateECD">
            <wsdl:input message="tns:ecdParam" name="ecdParam"/>
            <wsdl:output message="tns:result" name="result3"/>
        </wsdl:operation>
        
        <wsdl:operation name="addNote">
            <wsdl:input message="tns:note" name="note"/>
            <wsdl:output message="tns:result" name="result4"/>
        </wsdl:operation>

        <wsdl:operation name="addAttachment">
            <wsdl:input message="tns:attachment" name="attachment"/>
            <wsdl:output message="tns:result" name="result5"/>
        </wsdl:operation>

    </wsdl:portType>


    <wsdl:binding name="UploadServiceSOAP" type="tns:UploadService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />

        <wsdl:operation name="uploadBordereau">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/uploadBordereau" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>

            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>


        <wsdl:operation name="paymentReceived">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/paymentReceived" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>

            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="closeClaim">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/closeClaim" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>

            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="reopenClaim">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/reopenClaim" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>

            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="updateECD">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/updateECD" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>

            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        
        <wsdl:operation name="addNote">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/addNote" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        
        <wsdl:operation name="addAttachment">
            <soap:operation soapAction="http://www.idaschox.com/services/UploadService/addAttachment" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>


    <wsdl:service name="UploadService">
        <wsdl:port binding="tns:UploadServiceSOAP" name="UploadServiceSOAP">
            <!--soap:address location="http://localhost:8443/services/UploadService" /-->
            <!--soap:address location="https://test.idaschox.com:8443/services/UploadService" /-->
            <soap:address location="https://www.idaschox.com:8443/services/UploadService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
