<?xml version='1.0' encoding='UTF-8'?><xsd:schema elementFormDefault="qualified" jaxb:extensionBindingPrefixes="xjc" jaxb:version="2.0" targetNamespace="http://www.idaschox.com/service/CHOX/" xmlns:chx="http://www.idaschox.com/service/CHOX/" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!--  Specify simple bindings for the xjc compiler. This allows @XmlRootElement
          annotations to be generated for our elements (if/when needed) -->
    <xsd:annotation>
        <xsd:appinfo>
            <jaxb:globalBindings>
                <xjc:simple/>
            </jaxb:globalBindings>
        </xsd:appinfo>
    </xsd:annotation>

	<xsd:simpleType name="Char">
    	<xsd:restriction base="xsd:string">
       		<xsd:minLength value="0"/>
       		<xsd:maxLength value="1"/>
    	</xsd:restriction>
  	</xsd:simpleType>

  	<xsd:simpleType name="Money">
    	<xsd:restriction base="xsd:decimal">
       		<xsd:fractionDigits value="2"/>
    	</xsd:restriction>
  	</xsd:simpleType>

	<xsd:simpleType name="Money-or-empty">
		<xsd:union memberTypes="chx:Money chx:Empty-string"/>
	</xsd:simpleType>

	<xsd:simpleType name="Integer-or-empty">
		<xsd:union memberTypes="xsd:integer chx:Empty-string"/>
	</xsd:simpleType>

	<xsd:simpleType name="DateTime-or-empty">
		<xsd:union memberTypes="xsd:dateTime chx:Empty-string"/>
	</xsd:simpleType>

	<xsd:simpleType name="Empty-string">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value=""/>
		</xsd:restriction>
	</xsd:simpleType>

    <xsd:simpleType name="ExtraType">
        <xsd:annotation>
            <xsd:documentation>The extras type is used for invoice extras.</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
            <xsd:enumeration value="Admin"/>
            <xsd:enumeration value="Additional Driver"/>
            <xsd:enumeration value="Automatic"/>
            <xsd:enumeration value="Baby Seat"/>
            <xsd:enumeration value="CDW"/>
            <xsd:enumeration value="Delivery Collection"/>
            <xsd:enumeration value="Dual Control"/>
            <xsd:enumeration value="Estate"/>
            <xsd:enumeration value="Non-standard Risk Insurance Premium"/>
            <xsd:enumeration value="Roof Rack"/>
            <xsd:enumeration value="Sat Nav"/>
            <xsd:enumeration value="Tow Bars"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="VehicleExtras">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" name="extra" type="chx:ExtraType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RentalVehicle">
        <xsd:sequence>
            <xsd:element name="vehicle-registration" type="xsd:string"/>
            <xsd:element name="vehicle-manufacturer" type="xsd:string"/>
            <xsd:element name="vehicle-model" type="xsd:string"/>
            <xsd:element name="vehicle-class" type="xsd:string"/>
            <xsd:element name="rental-start" type="chx:DateTime-or-empty"/>
            <xsd:element name="rental-end" type="chx:DateTime-or-empty"/>
            <xsd:element name="collection-reason" type="xsd:string"/>
            <xsd:element name="rental-days" type="chx:Integer-or-empty"/>
            <xsd:element name="extras" type="chx:VehicleExtras"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RentalVehicles">
        <xsd:sequence>
            <xsd:element name="rental-vehicle" type="chx:RentalVehicle"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Driver">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="firstnames" type="xsd:string"/>
            <xsd:element name="lastname" type="xsd:string"/>
            <xsd:element name="address1" type="xsd:string"/>
            <xsd:element name="address2" type="xsd:string"/>
            <xsd:element name="address3" type="xsd:string"/>
            <xsd:element name="address4" type="xsd:string"/>
            <xsd:element name="address5" type="xsd:string"/>
            <xsd:element name="postcode" type="xsd:string"/>
            <xsd:element name="telephone-day" type="xsd:string"/>
            <xsd:element name="telephone-evening" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
            <xsd:element name="age" type="chx:Integer-or-empty"/>
            <xsd:element name="occupation" type="xsd:string"/>
            <xsd:element name="policy-usage" type="xsd:string"/>
            <xsd:element name="primary-driver" type="chx:Char"/>
            
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Drivers">
        <xsd:sequence>
            <xsd:element name="driver" type="chx:Driver"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="EngineerReport">
        <xsd:sequence>
            <xsd:element name="labour-amount" type="chx:Money-or-empty"/>
            <xsd:element name="total-amount" type="chx:Money-or-empty"/>
            <xsd:element name="days" type="chx:Integer-or-empty"/>
            <xsd:element name="usable" type="chx:Char"/>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="company" type="xsd:string"/>
            <xsd:element name="address1" type="xsd:string"/>
            <xsd:element name="address2" type="xsd:string"/>
            <xsd:element name="address3" type="xsd:string"/>
            <xsd:element name="address4" type="xsd:string"/>
            <xsd:element name="address5" type="xsd:string"/>
            <xsd:element name="postcode" type="xsd:string"/>
            <xsd:element name="telephone" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RepairDetails">
        <xsd:sequence>
            <xsd:element name="repairer" type="xsd:string"/>
            <xsd:element name="inspection-booked-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="inspection-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="repair-book-in-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="repair-authorised-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="repair-started-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="repair-complete-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="name-ime" type="xsd:string"/>
            <xsd:element name="labour-rate" type="chx:Money-or-empty"/>
            <xsd:element name="labour-hours" type="chx:Money-or-empty"/>
            <xsd:element name="labour-cost" type="chx:Money-or-empty"/>
            <xsd:element name="tl-offer-made-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="tl-offer-accepted-date" type="chx:DateTime-or-empty"/>
            <xsd:element name="tl-cheque-issued" type="chx:DateTime-or-empty"/>
            <xsd:element name="tl-cheque-received" type="chx:DateTime-or-empty"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Repair">
        <xsd:sequence>
            <xsd:element name="engineer-report" type="chx:EngineerReport"/>
            <xsd:element name="repair-details" type="chx:RepairDetails"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CustomerInsurer">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="policy-number" type="xsd:string"/>
            <xsd:element name="claim-reference" type="xsd:string"/>
            <xsd:element name="comprehensive" type="chx:Char"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="CustomerVehicle">
        <xsd:sequence>
            <xsd:element name="vehicle-registration" type="xsd:string"/>
            <xsd:element name="vehicle-manufacturer" type="xsd:string"/>
            <xsd:element name="vehicle-model" type="xsd:string"/>
            <xsd:element name="year-of-manufacture" type="xsd:string"/>
            <xsd:element name="vehicle-class" type="xsd:string"/>
            <xsd:element name="location" type="xsd:string"/>
            <xsd:element name="damage" type="xsd:string"/>
            <xsd:element name="usable" type="chx:Char"/>
            <xsd:element name="total-loss" type="chx:Char"/>
            <xsd:element name="initial-ecd" type="chx:DateTime-or-empty"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Mitigation">
        <xsd:sequence>
            <xsd:element name="access-another-vehicle" type="chx:Char"/>
            <xsd:element name="other-vehicle" type="xsd:string"/>
            <xsd:element name="other-vehicle-regular-user" type="chx:Char"/>
            <xsd:element name="entitled-courtesy-car" type="chx:Char"/>
            <xsd:element name="specific-required" type="chx:Char"/>
            <xsd:element name="why-specific" type="xsd:string"/>
            <xsd:element name="type-required" type="xsd:string"/>
            <xsd:element name="special-requirements" type="xsd:string"/>
            <xsd:element name="ave-daily-mileage" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Customer">
        <xsd:sequence>
            <xsd:element name="insurer" type="chx:CustomerInsurer"/>
            <xsd:element name="vehicle" type="chx:CustomerVehicle"/>
            <xsd:element name="mitigation" type="chx:Mitigation"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ThirdPartyInsurer">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="policy-number" type="xsd:string"/>
            <xsd:element name="claim-reference" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ThirdPartyVehicle">
        <xsd:sequence>
            <xsd:element name="vehicle-registration" type="xsd:string"/>
            <xsd:element name="vehicle-manufacturer" type="xsd:string"/>
            <xsd:element name="vehicle-model" type="xsd:string"/>
            <xsd:element name="vehicle-class" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ThirdPartyDriver">
        <xsd:sequence>
            <xsd:element name="title" type="xsd:string"/>
            <xsd:element name="firstnames" type="xsd:string"/>
            <xsd:element name="lastname" type="xsd:string"/>
            <xsd:element name="address1" type="xsd:string"/>
            <xsd:element name="address2" type="xsd:string"/>
            <xsd:element name="address3" type="xsd:string"/>
            <xsd:element name="address4" type="xsd:string"/>
            <xsd:element name="address5" type="xsd:string"/>
            <xsd:element name="postcode" type="xsd:string"/>
            <xsd:element name="telephone-day" type="xsd:string"/>
            <xsd:element name="telephone-evening" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ThirdParty">
        <xsd:sequence>
            <xsd:element name="insurer" type="chx:ThirdPartyInsurer"/>
            <xsd:element name="vehicle" type="chx:ThirdPartyVehicle"/>
            <xsd:element name="driver" type="chx:ThirdPartyDriver"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Witness">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="address1" type="xsd:string"/>
            <xsd:element name="address2" type="xsd:string"/>
            <xsd:element name="address3" type="xsd:string"/>
            <xsd:element name="address4" type="xsd:string"/>
            <xsd:element name="address5" type="xsd:string"/>
            <xsd:element name="postcode" type="xsd:string"/>
            <xsd:element name="telephone-day" type="xsd:string"/>
            <xsd:element name="telephone-evening" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Witnesses">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" name="witness" type="chx:Witness"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Solicitor">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="address1" type="xsd:string"/>
            <xsd:element name="address2" type="xsd:string"/>
            <xsd:element name="address3" type="xsd:string"/>
            <xsd:element name="address4" type="xsd:string"/>
            <xsd:element name="address5" type="xsd:string"/>
            <xsd:element name="postcode" type="xsd:string"/>
            <xsd:element name="telephone" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Injury">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="address1" type="xsd:string"/>
            <xsd:element name="address2" type="xsd:string"/>
            <xsd:element name="address3" type="xsd:string"/>
            <xsd:element name="address4" type="xsd:string"/>
            <xsd:element name="address5" type="xsd:string"/>
            <xsd:element name="postcode" type="xsd:string"/>
            <xsd:element name="telephone-day" type="xsd:string"/>
            <xsd:element name="telephone-evening" type="xsd:string"/>
            <xsd:element name="email" type="xsd:string"/>
            <xsd:element name="solicitor" type="chx:Solicitor"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Injuries">
        <xsd:sequence>
            <xsd:element maxOccurs="unbounded" name="injury" type="chx:Injury"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Incident">
        <xsd:sequence>
            <xsd:element name="date" type="chx:DateTime-or-empty"/>
            <xsd:element name="location" type="xsd:string"/>
            <xsd:element name="police-involved" type="chx:Char"/>
            <xsd:element name="description" type="xsd:string"/>
            <xsd:element name="witnesses" type="chx:Witnesses"/>
            <xsd:element name="injuries" type="chx:Injuries"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Claim">
        <xsd:sequence>
            <xsd:element name="customer" type="chx:Customer"/>
            <xsd:element name="third-party" type="chx:ThirdParty"/>
            <xsd:element name="incident" type="chx:Incident"/>
        </xsd:sequence>
    </xsd:complexType>



    <xsd:complexType name="Costs">
        <xsd:sequence>
            <xsd:element name="net" type="chx:Money-or-empty"/>
            <xsd:element name="vat" type="chx:Money-or-empty"/>
            <xsd:element name="gross" type="chx:Money-or-empty"/>
        </xsd:sequence>
    </xsd:complexType>


    <xsd:complexType name="Supplier">
        <xsd:sequence>
            <xsd:element name="excess-collected" type="chx:Money-or-empty"/>
            <xsd:element name="vat-collected" type="chx:Money-or-empty"/>
            <xsd:element name="handling-invoice-no" type="xsd:string"/>
            <xsd:element name="handling-invoice-amount" type="chx:Money-or-empty"/>
            <xsd:element name="claim-invoice-no" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Extra">
        <xsd:sequence>
            <xsd:element name="name" type="chx:ExtraType"/>
            <xsd:element name="quantity" type="chx:Integer-or-empty"/>
            <xsd:element name="item-cost" type="chx:Money-or-empty"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Extras">
        <xsd:sequence>
            <xsd:element name="cover-note-required" type="chx:Char"/>
            <xsd:element maxOccurs="unbounded" name="extra" type="chx:Extra"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Vehicles">
        <xsd:sequence>
            <xsd:element name="day-rate" type="chx:Money-or-empty"/>
            <xsd:element name="net" type="chx:Money-or-empty"/>
            <xsd:element name="vat" type="chx:Money-or-empty"/>
            <xsd:element name="gross" type="chx:Money-or-empty"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Invoice">
        <xsd:sequence>
            <xsd:element name="less-handling-fee" type="chx:Money-or-empty"/>
            <xsd:element name="net" type="chx:Money-or-empty"/>
            <xsd:element name="vat" type="chx:Money-or-empty"/>
            <xsd:element name="gross" type="chx:Money-or-empty"/>
            <xsd:element name="less-discount" type="chx:Money-or-empty"/>
            <xsd:element name="total-to-pay" type="chx:Money-or-empty"/>
            <xsd:element name="date-invoiced" type="chx:DateTime-or-empty"/>
            <xsd:element name="vehicles" type="chx:Vehicles"/>
            <xsd:element name="extras" type="chx:Extras"/>
            <xsd:element name="supplier" type="chx:Supplier"/>
            <xsd:element name="repair" type="chx:Costs"/>
            <xsd:element name="storage-recovery" type="chx:Costs"/>
            <xsd:element name="engineer-fee" type="chx:Costs"/>
            <xsd:element name="total-loss" type="chx:Costs"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="RentalSupplier">
        <xsd:sequence>
            <xsd:element name="supplier-name" type="xsd:string"/>
            <xsd:element name="supplier-reference" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>





    <xsd:complexType name="Chox">
        <xsd:sequence>
        	<xsd:element name="macroversion" type="xsd:decimal"/>
        	<xsd:element name="rental">
    			<xsd:complexType>
        			<xsd:sequence>
           				<xsd:element name="first-contact" type="chx:DateTime-or-empty"/>
            			<xsd:element name="supplier" type="chx:RentalSupplier"/>
            			<xsd:element name="managing-repair" type="chx:Char"/>
            			<xsd:element name="agreement-signed" type="chx:DateTime-or-empty"/>
            			<xsd:element name="gta-notice" type="chx:DateTime-or-empty"/>
            			<xsd:element name="invoice" type="chx:Invoice"/>
            			<xsd:element name="rental-status" type="xsd:string"/>
            			<xsd:element name="rental-vehicles" type="chx:RentalVehicles"/>
            			<xsd:element name="drivers" type="chx:Drivers"/>
            			<xsd:element name="claim" type="chx:Claim"/>
            			<xsd:element name="repair" type="chx:Repair"/>
        			</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
        </xsd:sequence>
    </xsd:complexType>


	<xsd:complexType name="SubmissionRequest">
		<xsd:sequence>
			<xsd:element name="chox" type="chx:Chox"/>
  		</xsd:sequence>
	</xsd:complexType>

    <xsd:complexType name="SubmissionResult">
        <xsd:sequence>
            <xsd:element name="status" type="xsd:boolean"/>
            <xsd:element name="uploadStatus" type="xsd:string"/>
            <xsd:element name="processStatus" type="xsd:string"/>
            <xsd:element name="claimParseStatus" type="xsd:string"/>
            <xsd:element name="claimStatus" type="xsd:string"/>
            <xsd:element name="Messages">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element maxOccurs="unbounded" name="message" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

<!-- To validate a CHOX xml file with this xsd, uncomment the following line:
	<xsd:element name="chox" type="chx:Chox"/>
-->

</xsd:schema>