#
# Rolling file appender 
#
log4j.appender.R=org.apache.log4j.RollingFileAppender
log4j.appender.R.File=wsClient.log
log4j.appender.R.MaxFileSize=10MB
log4j.appender.R.MaxBackupIndex=10
log4j.appender.R.layout=org.apache.log4j.PatternLayout
log4j.appender.R.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n


#
# Standard console appender 
#
log4j.appender.S=org.apache.log4j.ConsoleAppender
log4j.appender.S.layout=org.apache.log4j.PatternLayout
log4j.appender.S.layout.ConversionPattern=%d{dd MMM yyyy HH:mm:ss} %p %t %c - %m%n

log4j.rootCategory=ERROR
log4j.logger.org.apache.cxf=ERROR, S
log4j.logger.idas.chox=ERROR, S
